-- =============================================================================
-- BANDEIRAS - LIMPAR E INSERIR COM RESPOSTAS RANDOMIZADAS
-- Executar no SQL Editor do Supabase Dashboard
-- =============================================================================

-- Apagar perguntas antigas de bandeiras
DELETE FROM questions WHERE category = 'Bandeiras';

-- Inserir novas perguntas com respostas aleatórias
INSERT INTO questions (text, options, correct_option, image_url, category, age_rating, country_code) VALUES
('De que país é esta bandeira?', '["Reino Unido", "Guernsey", "França", "Jersey"]', 1, '/flags/gg.svg', 'Bandeiras', 18, 'GG'),
('De que país é esta bandeira?', '["Laos", "Tailândia", "Bangladesh", "Mianmar"]', 3, '/flags/mm.svg', 'Bandeiras', 18, 'MM'),
('De que país é esta bandeira?', '["Maurícia", "Moçambique", "Madagáscar", "Comores"]', 2, '/flags/mg.svg', 'Bandeiras', 18, 'MG'),
('De que país é esta bandeira?', '["Ilhas Caimão", "Ilhas Virgens Britânicas", "Jamaica", "Cuba"]', 0, '/flags/ky.svg', 'Bandeiras', 18, 'KY'),
('De que país é esta bandeira?', '["Austrália", "Nova Zelândia", "Nauru", "Quiribati"]', 2, '/flags/nr.svg', 'Bandeiras', 18, 'NR'),
('De que país é esta bandeira?', '["Quénia", "Camarões", "Nigéria", "Gana"]', 2, '/flags/ng.svg', 'Bandeiras', 18, 'NG'),
('De que país é esta bandeira?', '["Angola", "Botswana", "Namíbia", "África do Sul"]', 2, '/flags/na.svg', 'Bandeiras', 18, 'NA'),
('De que país é esta bandeira?', '["Síria", "Jordânia", "Líciano", "Israel"]', 2, '/flags/lb.svg', 'Bandeiras', 18, 'LB'),
('De que país é esta bandeira?', '["Marrocos", "Tunísia", "Argélia", "Líbia"]', 2, '/flags/dz.svg', 'Bandeiras', 18, 'DZ'),
('De que país é esta bandeira?', '["Quénia", "Sudão", "Etiópia", "Sudão do Sul"]', 3, '/flags/ss.svg', 'Bandeiras', 18, 'SS'),
('De que país é esta bandeira?', '["Itália", "Espanha", "México", "França"]', 2, '/flags/mx.svg', 'Bandeiras', 18, 'MX'),
('De que país é esta bandeira?', '["Trinidad e Tobago", "Haiti", "Jamaica", "Cuba"]', 2, '/flags/jm.svg', 'Bandeiras', 18, 'JM'),
('De que país é esta bandeira?', '["Bangladesh", "Paquistão", "Sri Lanka", "Índia"]', 2, '/flags/lk.svg', 'Bandeiras', 18, 'LK'),
('De que país é esta bandeira?', '["Marrocos", "Tunísia", "Argélia", "Líbia"]', 1, '/flags/tn.svg', 'Bandeiras', 18, 'TN'),
('De que país é esta bandeira?', '["Sudão", "Líbia", "Chade", "República Centro-Africana"]', 2, '/flags/td.svg', 'Bandeiras', 18, 'TD'),
('De que país é esta bandeira?', '["Coreia do Sul", "Japão", "Taiwan", "China"]', 2, '/flags/tw.svg', 'Bandeiras', 18, 'TW'),
('De que país é esta bandeira?', '["Argentina", "Uruguai", "Paraguai", "Brasil"]', 0, '/flags/ar.svg', 'Bandeiras', 18, 'AR'),
('De que país é esta bandeira?', '["Croácia", "Eslovénia", "Sérvia", "Bósnia-Herzegovina"]', 3, '/flags/ba.svg', 'Bandeiras', 18, 'BA'),
('De que país é esta bandeira?', '["Nicarágua", "Costa Rica", "Panamá", "Honduras"]', 1, '/flags/cr.svg', 'Bandeiras', 18, 'CR'),
('De que país é esta bandeira?', '["Bélgica", "Luxemburgo", "Holanda", "França"]', 3, '/flags/lu.svg', 'Bandeiras', 18, 'LU'),
('De que país é esta bandeira?', '["Taiwan", "Japão", "Coreia do Sul", "China"]', 0, '/flags/jp.svg', 'Bandeiras', 18, 'JP'),
('De que país é esta bandeira?', '["Gabão", "Camarões", "República do Congo", "Guiné Equatorial"]', 3, '/flags/gq.svg', 'Bandeiras', 18, 'GQ'),
('De que país é esta bandeira?', '["Chile", "Peru", "Colômbia", "Equador"]', 3, '/flags/ec.svg', 'Bandeiras', 18, 'EC'),
('De que país é esta bandeira?', '["Maldivas", "Índia", "Sri Lanka", "Indonésia"]', 0, '/flags/mv.svg', 'Bandeiras', 18, 'MV'),
('De que país é esta bandeira?', '["Costa do Marfim", "Senegal", "Burkina Faso", "Gana"]', 0, '/flags/ci.svg', 'Bandeiras', 18, 'CI'),
('De que país é esta bandeira?', '["Vietname", "Tailândia", "Camboja", "Laos"]', 0, '/flags/th.svg', 'Bandeiras', 18, 'TH'),
('De que país é esta bandeira?', '["Taiwan", "Hong Kong", "China", "Japão"]', 2, '/flags/cn.svg', 'Bandeiras', 18, 'CN'),
('De que país é esta bandeira?', '["São Martinho", "São Bartolomeu", "Guadalupe", "Martinica"]', 2, '/flags/bl.svg', 'Bandeiras', 18, 'BL'),
('De que país é esta bandeira?', '["Lituânia", "Letónia", "Estónia", "Rússia"]', 3, '/flags/ee.svg', 'Bandeiras', 18, 'EE'),
('De que país é esta bandeira?', '["Espanha", "França", "Portugal", "Andorra"]', 3, '/flags/ad.svg', 'Bandeiras', 18, 'AD'),
('De que país é esta bandeira?', '["Nigéria", "Gana", "Costa do Marfim", "Senegal"]', 1, '/flags/gh.svg', 'Bandeiras', 18, 'GH'),
('De que país é esta bandeira?', '["República Checa", "Eslováquia", "Polónia", "Hungria"]', 2, '/flags/pl.svg', 'Bandeiras', 18, 'PL'),
('De que país é esta bandeira?', '["Marrocos", "Argélia", "Tunísia", "Líbia"]', 1, '/flags/ma.svg', 'Bandeiras', 18, 'MA'),
('De que país é esta bandeira?', '["Lituânia", "Letónia", "Estónia", "Polónia"]', 1, '/flags/lv.svg', 'Bandeiras', 18, 'LV'),
('De que país é esta bandeira?', '["Costa Rica", "Panamá", "Nicarágua", "Colômbia"]', 1, '/flags/pa.svg', 'Bandeiras', 18, 'PA'),
('De que país é esta bandeira?', '["Gabão", "Nigéria", "Camarões", "República do Congo"]', 0, '/flags/ga.svg', 'Bandeiras', 18, 'GA'),
('De que país é esta bandeira?', '["Moldávia", "Roménia", "Ucrânia", "Bielorrússia"]', 2, '/flags/by.svg', 'Bandeiras', 18, 'BY'),
('De que país é esta bandeira?', '["República Centro-Africana", "Chade", "Camarões", "Congo"]', 1, '/flags/cf.svg', 'Bandeiras', 18, 'CF'),
('De que país é esta bandeira?', '["Chipre", "Grécia", "Turquia", "Malta"]', 0, '/flags/cy.svg', 'Bandeiras', 18, 'CY'),
('De que país é esta bandeira?', '["Tanzânia", "Uganda", "Quénia", "Ruanda"]', 3, '/flags/tz.svg', 'Bandeiras', 18, 'TZ'),
('De que país é esta bandeira?', '["Egito", "Líbia", "Sudão", "Etiópia"]', 0, '/flags/eg.svg', 'Bandeiras', 18, 'EG'),
('De que país é esta bandeira?', '["Tajiquistão", "Uzbequistão", "Afeganistão", "China"]', 0, '/flags/tj.svg', 'Bandeiras', 18, 'TJ'),
('De que país é esta bandeira?', '["Fiji", "Samoa", "Tonga", "Nova Zelândia"]', 3, '/flags/nz.svg', 'Bandeiras', 18, 'NZ'),
('De que país é esta bandeira?', '["Nigéria", "Camarões", "Gabão", "República do Congo"]', 3, '/flags/cg.svg', 'Bandeiras', 18, 'CG'),
('De que país é esta bandeira?', '["Moçambique", "Zâmbia", "Zimbabwe", "Malawi"]', 0, '/flags/mz.svg', 'Bandeiras', 18, 'MZ'),
('De que país é esta bandeira?', '["Irlanda", "Reino Unido", "Islândia", "Noruega"]', 1, '/flags/ie.svg', 'Bandeiras', 18, 'IE'),
('De que país é esta bandeira?', '["Quirguistão", "Cazaquistão", "Uzbequistão", "Tajiquistão"]', 2, '/flags/uz.svg', 'Bandeiras', 18, 'UZ'),
('De que país é esta bandeira?', '["Gabão", "Nigéria", "Camarões", "República do Congo"]', 0, '/flags/cm.svg', 'Bandeiras', 18, 'CM'),
('De que país é esta bandeira?', '["São Tomé e Príncipe", "Gabão", "Nigéria", "Guiné Equatorial"]', 3, '/flags/st.svg', 'Bandeiras', 18, 'ST'),
('De que país é esta bandeira?', '["Maurícia", "Seicheles", "Madagáscar", "Comores"]', 1, '/flags/sc.svg', 'Bandeiras', 18, 'SC'),
('De que país é esta bandeira?', '["Vaticano", "Itália", "Mónaco", "San Marino"]', 1, '/flags/va.svg', 'Bandeiras', 18, 'VA'),
('De que país é esta bandeira?', '["Gana", "Nigéria", "Costa do Marfim", "Togo"]', 3, '/flags/tg.svg', 'Bandeiras', 18, 'TG'),
('De que país é esta bandeira?', '["Filipinas", "Indonésia", "Malásia", "Brunei"]', 1, '/flags/ph.svg', 'Bandeiras', 18, 'PH'),
('De que país é esta bandeira?', '["Nigéria", "Níger", "Burkina Faso", "Mali"]', 1, '/flags/ne.svg', 'Bandeiras', 18, 'NE'),
('De que país é esta bandeira?', '["Irão", "Iraque", "Paquistão", "Afeganistão"]', 0, '/flags/ir.svg', 'Bandeiras', 18, 'IR'),
('De que país é esta bandeira?', '["Tailândia", "Mianmar", "Laos", "Camboja"]', 3, '/flags/kh.svg', 'Bandeiras', 18, 'KH'),
('De que país é esta bandeira?', '["Gronelândia", "Canadá", "Dinamarca", "Islândia"]', 1, '/flags/gl.svg', 'Bandeiras', 18, 'GL'),
('De que país é esta bandeira?', '["Malta", "Chipre", "Itália", "Grécia"]', 0, '/flags/mt.svg', 'Bandeiras', 18, 'MT'),
('De que país é esta bandeira?', '["Irlanda", "Reino Unido", "Escócia", "País de Gales"]', 2, '/flags/gb.svg', 'Bandeiras', 18, 'GB'),
('De que país é esta bandeira?', '["Malásia", "Indonésia", "Singapura", "Brunei"]', 0, '/flags/my.svg', 'Bandeiras', 18, 'MY'),
('De que país é esta bandeira?', '["Mónaco", "França", "Itália", "Espanha"]', 0, '/flags/mc.svg', 'Bandeiras', 18, 'MC'),
('De que país é esta bandeira?', '["Cuba", "República Dominicana", "Jamaica", "Haiti"]', 3, '/flags/do.svg', 'Bandeiras', 18, 'DO'),
('De que país é esta bandeira?', '["Omã", "Iémen", "Arábia Saudita", "Emirados Árabes Unidos"]', 0, '/flags/om.svg', 'Bandeiras', 18, 'OM'),
('De que país é esta bandeira?', '["Serra Leoa", "Guiné", "Libéria", "Costa do Marfim"]', 0, '/flags/sl.svg', 'Bandeiras', 18, 'SL'),
('De que país é esta bandeira?', '["República Checa", "Eslováquia", "Polónia", "Áustria"]', 3, '/flags/cz.svg', 'Bandeiras', 18, 'CZ'),
('De que país é esta bandeira?', '["Bielorrússia", "Ucrânia", "Rússia", "Polónia"]', 0, '/flags/ru.svg', 'Bandeiras', 18, 'RU'),
('De que país é esta bandeira?', '["Barbados", "Trinidad e Tobago", "Jamaica", "Bahamas"]', 1, '/flags/tt.svg', 'Bandeiras', 18, 'TT'),
('De que país é esta bandeira?', '["Ilhas Faroé", "Dinamarca", "Islândia", "Noruega"]', 0, '/flags/fo.svg', 'Bandeiras', 18, 'FO'),
('De que país é esta bandeira?', '["Mali", "Senegal", "Burkina Faso", "Níger"]', 1, '/flags/ml.svg', 'Bandeiras', 18, 'ML'),
('De que país é esta bandeira?', '["Benin", "Nigéria", "Burkina Faso", "Togo"]', 0, '/flags/bj.svg', 'Bandeiras', 18, 'BJ'),
('De que país é esta bandeira?', '["Camarões", "Nigéria", "Gabão", "República do Congo"]', 1, '/flags/cg.svg', 'Bandeiras', 18, 'CG'),
('De que país é esta bandeira?', '["Malásia", "Indonésia", "Filipinas", "Singapura"]', 1, '/flags/id.svg', 'Bandeiras', 18, 'ID'),
('De que país é esta bandeira?', '["Gana", "Nigéria", "Costa do Marfim", "Senegal"]', 0, '/flags/sn.svg', 'Bandeiras', 18, 'SN'),
('De que país é esta bandeira?', '["Polinésia Francesa", "Nova Zelândia", "Austrália", "Hawai"]', 0, '/flags/pf.svg', 'Bandeiras', 18, 'PF'),
('De que país é esta bandeira?', '["Macedónia do Norte", "Grécia", "Albânia", "Bulgária"]', 0, '/flags/mk.svg', 'Bandeiras', 18, 'MK'),
('De que país é esta bandeira?', '["Israel", "Jordânia", "Síria", "Líciano"]', 3, '/flags/jo.svg', 'Bandeiras', 18, 'JO'),
('De que país é esta bandeira?', '["Bolívia", "Chile", "Peru", "Paraguai"]', 0, '/flags/bo.svg', 'Bandeiras', 18, 'BO'),
('De que país é esta bandeira?', '["Guatemala", "Honduras", "El Salvador", "Nicarágua"]', 0, '/flags/gt.svg', 'Bandeiras', 18, 'GT'),
('De que país é esta bandeira?', '["Brasil", "Portugal", "Argentina", "Espanha"]', 0, '/flags/br.svg', 'Bandeiras', 18, 'BR'),
('De que país é esta bandeira?', '["Porto Rico", "Cuba", "República Dominicana", "Estados Unidos"]', 3, '/flags/pr.svg', 'Bandeiras', 18, 'PR'),
('De que país é esta bandeira?', '["Gâmbia", "Senegal", "Guiné", "Mauritânia"]', 0, '/flags/gm.svg', 'Bandeiras', 18, 'GM'),
('De que país é esta bandeira?', '["Kosovo", "Albânia", "Sérvia", "Montenegro"]', 0, '/flags/xk.svg', 'Bandeiras', 18, 'XK'),
('De que país é esta bandeira?', '["Burundi", "Ruanda", "Uganda", "Tanzânia"]', 0, '/flags/bi.svg', 'Bandeiras', 18, 'BI'),
('De que país é esta bandeira?', '["Suazilândia", "Lesoto", "África do Sul", "Botswana"]', 1, '/flags/ls.svg', 'Bandeiras', 18, 'LS'),
('De que país é esta bandeira?', '["Guiné-Bissau", "Senegal", "Guiné", "Gâmbia"]', 0, '/flags/gw.svg', 'Bandeiras', 18, 'GW'),
('De que país é esta bandeira?', '["Malawi", "Moçambique", "Zâmbia", "Tanzânia"]', 3, '/flags/mw.svg', 'Bandeiras', 18, 'MW'),
('De que país é esta bandeira?', '["El Salvador", "Guatemala", "Honduras", "Nicarágua"]', 2, '/flags/hn.svg', 'Bandeiras', 18, 'HN'),
('De que país é esta bandeira?', '["Mongólia", "Rússia", "China", "Cazaquistão"]', 0, '/flags/mn.svg', 'Bandeiras', 18, 'MN'),
('De que país é esta bandeira?', '["Zimbabwe", "Zâmbia", "Botswana", "Moçambique"]', 1, '/flags/zm.svg', 'Bandeiras', 18, 'ZM'),
('De que país é esta bandeira?', '["Tunísia", "Argélia", "Marrocos", "Líbia"]', 0, '/flags/tn.svg', 'Bandeiras', 18, 'TN'),
('De que país é esta bandeira?', '["Cazaquistão", "Uzbequistão", "Turquemenistão", "Quirguistão"]', 3, '/flags/kg.svg', 'Bandeiras', 18, 'KG'),
('De que país é esta bandeira?', '["Guam", "Filipinas", "Austrália", "Estados Unidos"]', 3, '/flags/gu.svg', 'Bandeiras', 18, 'GU'),
('De que país é esta bandeira?', '["Lituânia", "Polónia", "Letónia", "Estónia"]', 0, '/flags/lt.svg', 'Bandeiras', 18, 'LT'),
('De que país é esta bandeira?', '["Guadalupe", "Martinica", "São Martinho", "São Bartolomeu"]', 0, '/flags/gp.svg', 'Bandeiras', 18, 'GP'),
('De que país é esta bandeira?', '["Vanuatu", "Fiji", "Papua Nova Guiné", "Austrália"]', 1, '/flags/fj.svg', 'Bandeiras', 18, 'FJ'),
('De que país é esta bandeira?', '["Ilhas Salomão", "Papua Nova Guiné", "Fiji", "Austrália"]', 0, '/flags/sb.svg', 'Bandeiras', 18, 'SB'),
('De que país é esta bandeira?', '["Mauritânia", "Senegal", "Mali", "Marrocos"]', 0, '/flags/mr.svg', 'Bandeiras', 18, 'MR'),
('De que país é esta bandeira?', '["Portugal", "Espanha", "França", "Itália"]', 0, '/flags/pt.svg', 'Bandeiras', 18, 'PT'),
('De que país é esta bandeira?', '["Comores", "Madagáscar", "Maurícia", "Seicheles"]', 0, '/flags/km.svg', 'Bandeiras', 18, 'KM'),
('De que país é esta bandeira?', '["Nigéria", "Camarões", "Gabão", "Guiné Equatorial"]', 2, '/flags/gq.svg', 'Bandeiras', 18, 'GQ'),
('De que país é esta bandeira?', '["Bolívia", "Paraguai", "Uruguai", "Brasil"]', 3, '/flags/uy.svg', 'Bandeiras', 18, 'UY'),
('De que país é esta bandeira?', '["Quirguistão", "Tajiquistão", "Uzbequistão", "Cazaquistão"]', 1, '/flags/tm.svg', 'Bandeiras', 18, 'TM'),
('De que país é esta bandeira?', '["Ruanda", "Uganda", "Tanzânia", "Burundi"]', 0, '/flags/rw.svg', 'Bandeiras', 18, 'RW'),
('De que país é esta bandeira?', '["Estados Unidos", "Canadá", "México", "Reino Unido"]', 0, '/flags/us.svg', 'Bandeiras', 18, 'US'),
('De que país é esta bandeira?', '["Espanha", "Portugal", "França", "Itália"]', 2, '/flags/fr.svg', 'Bandeiras', 18, 'FR'),
('De que país é esta bandeira?', '["Uganda", "Quénia", "Tanzânia", "Ruanda"]', 1, '/flags/ug.svg', 'Bandeiras', 18, 'UG'),
('De que país é esta bandeira?', '["Suécia", "Noruega", "Dinamarca", "Finlândia"]', 0, '/flags/se.svg', 'Bandeiras', 18, 'SE'),
('De que país é esta bandeira?', '["República do Congo", "República Democrática do Congo", "Angola", "Ruanda"]', 2, '/flags/cd.svg', 'Bandeiras', 18, 'CD'),
('De que país é esta bandeira?', '["Colômbia", "Venezuela", "Equador", "Peru"]', 3, '/flags/pe.svg', 'Bandeiras', 18, 'PE'),
('De que país é esta bandeira?', '["Nova Caledónia", "Fiji", "Vanuatu", "Austrália"]', 1, '/flags/nc.svg', 'Bandeiras', 18, 'NC'),
('De que país é esta bandeira?', '["Ilhas Marshall", "Quiribati", "Micronésia", "Palau"]', 3, '/flags/pw.svg', 'Bandeiras', 18, 'PW'),
('De que país é esta bandeira?', '["Bélgica", "Holanda", "Alemanha", "França"]', 0, '/flags/nl.svg', 'Bandeiras', 18, 'NL'),
('De que país é esta bandeira?', '["São Vicente e Granadinas", "Granada", "Santa Lúcia", "Barbados"]', 3, '/flags/vc.svg', 'Bandeiras', 18, 'VC'),
('De que país é esta bandeira?', '["Venezuela", "Colômbia", "Brasil", "Peru"]', 0, '/flags/ve.svg', 'Bandeiras', 18, 'VE'),
('De que país é esta bandeira?', '["Eritreia", "Etiópia", "Djibouti", "Somália"]', 0, '/flags/er.svg', 'Bandeiras', 18, 'ER'),
('De que país é esta bandeira?', '["Bahamas", "Cuba", "Jamaica", "República Dominicana"]', 2, '/flags/bs.svg', 'Bandeiras', 18, 'BS'),
('De que país é esta bandeira?', '["Burkina Faso", "Mali", "Níger", "Benin"]', 0, '/flags/bf.svg', 'Bandeiras', 18, 'BF'),
('De que país é esta bandeira?', '["Sérvia", "Croácia", "Eslovénia", "Montenegro"]', 1, '/flags/me.svg', 'Bandeiras', 18, 'ME'),
('De que país é esta bandeira?', '["Nigéria", "Gabão", "Camarões", "República do Congo"]', 2, '/flags/cm.svg', 'Bandeiras', 18, 'CM'),
('De que país é esta bandeira?', '["Jordânia", "Síria", "Israel", "Líciano"]', 2, '/flags/lb.svg', 'Bandeiras', 18, 'LB'),
('De que país é esta bandeira?', '["Israel", "Palestina", "Líciano", "Jordânia"]', 0, '/flags/il.svg', 'Bandeiras', 18, 'IL'),
('De que país é esta bandeira?', '["Hong Kong", "Taiwan", "China", "Japão"]', 2, '/flags/hk.svg', 'Bandeiras', 18, 'HK'),
('De que país é esta bandeira?', '["Paquistão", "Índia", "Afeganistão", "Bangladesh"]', 1, '/flags/pk.svg', 'Bandeiras', 18, 'PK'),
('De que país é esta bandeira?', '["Nigéria", "Gana", "Camarões", "Benin"]', 3, '/flags/bj.svg', 'Bandeiras', 18, 'BJ'),
('De que país é esta bandeira?', '["Samoa", "Fiji", "Tonga", "Quiribati"]', 0, '/flags/ws.svg', 'Bandeiras', 18, 'WS'),
('De que país é esta bandeira?', '["Angola", "Namíbia", "Botswana", "África do Sul"]', 3, '/flags/na.svg', 'Bandeiras', 18, 'NA'),
('De que país é esta bandeira?', '["Sérvia", "Croácia", "Eslovénia", "Bósnia-Herzegovina"]', 1, '/flags/hr.svg', 'Bandeiras', 18, 'HR'),
('De que país é esta bandeira?', '["Nigéria", "Costa do Marfim", "Gana", "Senegal"]', 1, '/flags/ci.svg', 'Bandeiras', 18, 'CI'),
('De que país é esta bandeira?', '["Gabão", "Nigéria", "Camarões", "República do Congo"]', 0, '/flags/ga.svg', 'Bandeiras', 18, 'GA'),
('De que país é esta bandeira?', '["Timor-Leste", "Indonésia", "Portugal", "Austrália"]', 0, '/flags/tl.svg', 'Bandeiras', 18, 'TL'),
('De que país é esta bandeira?', '["Liechtenstein", "Suíça", "Áustria", "Alemanha"]', 0, '/flags/li.svg', 'Bandeiras', 18, 'LI'),
('De que país é esta bandeira?', '["Albânia", "Grécia", "Itália", "Macedónia do Norte"]', 0, '/flags/al.svg', 'Bandeiras', 18, 'AL'),
('De que país é esta bandeira?', '["Argentina", "Chile", "Uruguai", "Brasil"]', 3, '/flags/py.svg', 'Bandeiras', 18, 'PY'),
('De que país é esta bandeira?', '["Quirguistão", "Cazaquistão", "Uzbequistão", "Tajiquistão"]', 1, '/flags/kz.svg', 'Bandeiras', 18, 'KZ'),
('De que país é esta bandeira?', '["Nauru", "Quiribati", "Fiji", "Austrália"]', 0, '/flags/nr.svg', 'Bandeiras', 18, 'NR'),
('De que país é esta bandeira?', '["Djibouti", "Etiópia", "Eritreia", "Somália"]', 2, '/flags/dj.svg', 'Bandeiras', 18, 'DJ'),
('De que país é esta bandeira?', '["Gana", "Nigéria", "Costa do Marfim", "Senegal"]', 1, '/flags/gh.svg', 'Bandeiras', 18, 'GH'),
('De que país é esta bandeira?', '["Cabo Verde", "Senegal", "Guiné-Bissau", "Mauritânia"]', 0, '/flags/cv.svg', 'Bandeiras', 18, 'CV'),
('De que país é esta bandeira?', '["Moldávia", "Roménia", "Ucrânia", "Rússia"]', 0, '/flags/md.svg', 'Bandeiras', 18, 'MD'),
('De que país é esta bandeira?', '["Ilhas Virgens Britânicas", "Ilhas Caimão", "Anguilla", "Porto Rico"]', 0, '/flags/vg.svg', 'Bandeiras', 18, 'VG'),
('De que país é esta bandeira?', '["Islândia", "Noruega", "Finlândia", "Dinamarca"]', 0, '/flags/is.svg', 'Bandeiras', 18, 'IS'),
('De que país é esta bandeira?', '["Jersey", "Reino Unido", "França", "Guernsey"]', 2, '/flags/je.svg', 'Bandeiras', 18, 'JE'),
('De que país é esta bandeira?', '["Finlândia", "Suécia", "Noruega", "Dinamarca"]', 0, '/flags/fi.svg', 'Bandeiras', 18, 'FI'),
('De que país é esta bandeira?', '["Ilha de Man", "Reino Unido", "Irlanda", "Escócia"]', 0, '/flags/im.svg', 'Bandeiras', 18, 'IM'),
('De que país é esta bandeira?', '["Geórgia", "Rússia", "Turquia", "Azerbaijão"]', 0, '/flags/ge.svg', 'Bandeiras', 18, 'GE'),
('De que país é esta bandeira?', '["Maldivas", "Índia", "Sri Lanka", "Indonésia"]', 0, '/flags/mv.svg', 'Bandeiras', 18, 'MV'),
('De que país é esta bandeira?', '["Singapura", "Malásia", "Indonésia", "Brunei"]', 0, '/flags/sg.svg', 'Bandeiras', 18, 'SG'),
('De que país é esta bandeira?', '["Argentina", "Chile", "Peru", "Colômbia"]', 3, '/flags/cl.svg', 'Bandeiras', 18, 'CL'),
('De que país é esta bandeira?', '["Nigéria", "Níger", "Mali", "Burkina Faso"]', 1, '/flags/ne.svg', 'Bandeiras', 18, 'NE'),
('De que país é esta bandeira?', '["Costa Rica", "Panamá", "Nicarágua", "Honduras"]', 1, '/flags/cr.svg', 'Bandeiras', 18, 'CR'),
('De que país é esta bandeira?', '["Brasil", "Portugal", "Espanha", "Argentina"]', 3, '/flags/ar.svg', 'Bandeiras', 18, 'AR'),
('De que país é esta bandeira?', '["Nigéria", "Gana", "Camarões", "Gabão"]', 1, '/flags/ng.svg', 'Bandeiras', 18, 'NG'),
('De que país é esta bandeira?', '["Irão", "Iraque", "Afeganistão", "Paquistão"]', 1, '/flags/iq.svg', 'Bandeiras', 18, 'IQ'),
('De que país é esta bandeira?', '["Tonga", "Fiji", "Samoa", "Nova Zelândia"]', 1, '/flags/to.svg', 'Bandeiras', 18, 'TO'),
('De que país é esta bandeira?', '["Uruguai", "Argentina", "Paraguai", "Brasil"]', 1, '/flags/uy.svg', 'Bandeiras', 18, 'UY'),
('De que país é esta bandeira?', '["Malta", "Chipre", "Grécia", "Itália"]', 1, '/flags/cy.svg', 'Bandeiras', 18, 'CY'),
('De que país é esta bandeira?', '["Arménia", "Azerbaijão", "Geórgia", "Rússia"]', 1, '/flags/az.svg', 'Bandeiras', 18, 'AZ'),
('De que país é esta bandeira?', '["Sérvia", "Croácia", "Eslovénia", "Eslováquia"]', 2, '/flags/si.svg', 'Bandeiras', 18, 'SI'),
('De que país é esta bandeira?', '["Espanha", "França", "Itália", "Portugal"]', 1, '/flags/es.svg', 'Bandeiras', 18, 'ES'),
('De que país é esta bandeira?', '["Líbia", "Egito", "Tunísia", "Argélia"]', 0, '/flags/ly.svg', 'Bandeiras', 18, 'LY'),
('De que país é esta bandeira?', '["Nigéria", "Gabão", "Camarões", "República do Congo"]', 1, '/flags/cg.svg', 'Bandeiras', 18, 'CG'),
('De que país é esta bandeira?', '["Guiné", "Senegal", "Mali", "Costa do Marfim"]', 0, '/flags/gn.svg', 'Bandeiras', 18, 'GN'),
('De que país é esta bandeira?', '["Bermudas", "Reino Unido", "Canadá", "Estados Unidos"]', 0, '/flags/bm.svg', 'Bandeiras', 18, 'BM'),
('De que país é esta bandeira?', '["Nigéria", "Gana", "Costa do Marfim", "Senegal"]', 1, '/flags/sn.svg', 'Bandeiras', 18, 'SN'),
('De que país é esta bandeira?', '["Nigéria", "Costa do Marfim", "Gana", "Senegal"]', 2, '/flags/ci.svg', 'Bandeiras', 18, 'CI'),
('De que país é esta bandeira?', '["São Cristóvão e Nevis", "Antígua e Barbuda", "Dominica", "Santa Lúcia"]', 0, '/flags/kn.svg', 'Bandeiras', 18, 'KN'),
('De que país é esta bandeira?', '["Dominica", "Santa Lúcia", "Granada", "Antígua e Barbuda"]', 0, '/flags/dm.svg', 'Bandeiras', 18, 'DM'),
('De que país é esta bandeira?', '["Granada", "São Vicente e Granadinas", "Santa Lúcia", "Barbados"]', 0, '/flags/gd.svg', 'Bandeiras', 18, 'GD'),
('De que país é esta bandeira?', '["Santa Lúcia", "São Vicente e Granadinas", "Granada", "Barbados"]', 0, '/flags/lc.svg', 'Bandeiras', 18, 'LC'),
('De que país é esta bandeira?', '["Antígua e Barbuda", "São Cristóvão e Nevis", "Dominica", "Granada"]', 0, '/flags/ag.svg', 'Bandeiras', 18, 'AG'),
('De que país é esta bandeira?', '["Argentina", "Brasil", "Uruguai", "Paraguai"]', 1, '/flags/br.svg', 'Bandeiras', 18, 'BR'),
('De que país é esta bandeira?', '["Alemanha", "Bélgica", "Suíça", "Áustria"]', 0, '/flags/de.svg', 'Bandeiras', 18, 'DE'),
('De que país é esta bandeira?', '["Itália", "Espanha", "França", "Grécia"]', 0, '/flags/it.svg', 'Bandeiras', 18, 'IT'),
('De que país é esta bandeira?', '["Suíça", "Áustria", "Alemanha", "Liechtenstein"]', 0, '/flags/ch.svg', 'Bandeiras', 18, 'CH'),
('De que país é esta bandeira?', '["Áustria", "Suíça", "Alemanha", "Hungria"]', 0, '/flags/at.svg', 'Bandeiras', 18, 'AT'),
('De que país é esta bandeira?', '["Grécia", "Itália", "Chipre", "Albânia"]', 0, '/flags/gr.svg', 'Bandeiras', 18, 'GR'),
('De que país é esta bandeira?', '["Noruega", "Suécia", "Dinamarca", "Islândia"]', 0, '/flags/no.svg', 'Bandeiras', 18, 'NO'),
('De que país é esta bandeira?', '["Dinamarca", "Noruega", "Suécia", "Finlândia"]', 0, '/flags/dk.svg', 'Bandeiras', 18, 'DK'),
('De que país é esta bandeira?', '["Ucrânia", "Rússia", "Bielorrússia", "Moldávia"]', 0, '/flags/ua.svg', 'Bandeiras', 18, 'UA'),
('De que país é esta bandeira?', '["Hungria", "Áustria", "Roménia", "Sérvia"]', 0, '/flags/hu.svg', 'Bandeiras', 18, 'HU'),
('De que país é esta bandeira?', '["Roménia", "Hungria", "Moldávia", "Bulgária"]', 0, '/flags/ro.svg', 'Bandeiras', 18, 'RO'),
('De que país é esta bandeira?', '["Bulgária", "Roménia", "Grécia", "Sérvia"]', 0, '/flags/bg.svg', 'Bandeiras', 18, 'BG'),
('De que país é esta bandeira?', '["Sérvia", "Croácia", "Eslovénia", "Bósnia-Herzegovina"]', 0, '/flags/rs.svg', 'Bandeiras', 18, 'RS'),
('De que país é esta bandeira?', '["Eslováquia", "República Checa", "Eslovénia", "Polónia"]', 0, '/flags/sk.svg', 'Bandeiras', 18, 'SK'),
('De que país é esta bandeira?', '["Azerbaijão", "Arménia", "Rússia", "Irão"]', 2, '/flags/am.svg', 'Bandeiras', 18, 'AM'),
('De que país é esta bandeira?', '["Indonésia", "Malásia", "Filipinas", "Singapura"]', 3, '/flags/ph.svg', 'Bandeiras', 18, 'PH'),
('De que país é esta bandeira?', '["Austrália", "Nova Zelândia", "Reino Unido", "Fiji"]', 0, '/flags/au.svg', 'Bandeiras', 18, 'AU'),
('De que país é esta bandeira?', '["Tailândia", "Vietname", "Laos", "Camboja"]', 1, '/flags/vn.svg', 'Bandeiras', 18, 'VN'),
('De que país é esta bandeira?', '["Índia", "Paquistão", "Bangladesh", "Sri Lanka"]', 0, '/flags/in.svg', 'Bandeiras', 18, 'IN'),
('De que país é esta bandeira?', '["Coreia do Sul", "Japão", "China", "Singapura"]', 0, '/flags/kr.svg', 'Bandeiras', 18, 'KR'),
('De que país é esta bandeira?', '["Rússia", "Ucrânia", "Bielorrússia", "Cazaquistão"]', 3, '/flags/kz.svg', 'Bandeiras', 18, 'KZ'),
('De que país é esta bandeira?', '["Turquia", "Grécia", "Chipre", "Síria"]', 0, '/flags/tr.svg', 'Bandeiras', 18, 'TR'),
('De que país é esta bandeira?', '["Emirados Árabes Unidos", "Arábia Saudita", "Qatar", "Koweit"]', 0, '/flags/ae.svg', 'Bandeiras', 18, 'AE'),
('De que país é esta bandeira?', '["Arábia Saudita", "Emirados Árabes Unidos", "Qatar", "Omã"]', 0, '/flags/sa.svg', 'Bandeiras', 18, 'SA'),
('De que país é esta bandeira?', '["Egito", "Marrocos", "Argélia", "Tunísia"]', 2, '/flags/et.svg', 'Bandeiras', 18, 'ET'),
('De que país é esta bandeira?', '["África do Sul", "Nigéria", "Quénia", "Gana"]', 0, '/flags/za.svg', 'Bandeiras', 18, 'ZA'),
('De que país é esta bandeira?', '["Quénia", "Tanzânia", "Uganda", "Etiópia"]', 0, '/flags/ke.svg', 'Bandeiras', 18, 'KE'),
('De que país é esta bandeira?', '["Etiópia", "Quénia", "Somália", "Eritreia"]', 0, '/flags/et.svg', 'Bandeiras', 18, 'ET'),
('De que país é esta bandeira?', '["Papua Nova Guiné", "Austrália", "Fiji", "Indonésia"]', 0, '/flags/pg.svg', 'Bandeiras', 18, 'PG'),
('De que país é esta bandeira?', '["Brasil", "Portugal", "Argentina", "Espanha"]', 3, '/flags/pt.svg', 'Bandeiras', 18, 'PT'),
('De que país é esta bandeira?', '["Nigéria", "Gana", "Camarões", "Costa do Marfim"]', 3, '/flags/ci.svg', 'Bandeiras', 18, 'CI'),
('De que país é esta bandeira?', '["Canadá", "Estados Unidos", "Reino Unido", "França"]', 0, '/flags/ca.svg', 'Bandeiras', 18, 'CA'),
('De que país é esta bandeira?', '["Cuba", "Jamaica", "Haiti", "República Dominicana"]', 0, '/flags/cu.svg', 'Bandeiras', 18, 'CU'),
('De que país é esta bandeira?', '["Jamaica", "Cuba", "Haiti", "Trinidad e Tobago"]', 3, '/flags/jm.svg', 'Bandeiras', 18, 'JM'),
('De que país é esta bandeira?', '["Mianmar", "Tailândia", "Laos", "Bangladesh"]', 0, '/flags/mm.svg', 'Bandeiras', 18, 'MM'),
('De que país é esta bandeira?', '["Bangladesh", "Índia", "Mianmar", "Sri Lanka"]', 0, '/flags/bd.svg', 'Bandeiras', 18, 'BD'),
('De que país é esta bandeira?', '["Afeganistão", "Paquistão", "Irão", "Turquemenistão"]', 0, '/flags/af.svg', 'Bandeiras', 18, 'AF'),
('De que país é esta bandeira?', '["Nepal", "Índia", "China", "Butão"]', 0, '/flags/np.svg', 'Bandeiras', 18, 'NP'),
('De que país é esta bandeira?', '["Butão", "Índia", "China", "Nepal"]', 1, '/flags/bt.svg', 'Bandeiras', 18, 'BT'),
('De que país é esta bandeira?', '["Laos", "Tailândia", "Vietname", "Camboja"]', 2, '/flags/la.svg', 'Bandeiras', 18, 'LA'),
('De que país é esta bandeira?', '["Brunei", "Malásia", "Indonésia", "Singapura"]', 3, '/flags/bn.svg', 'Bandeiras', 18, 'BN'),
('De que país é esta bandeira?', '["Macau", "China", "Hong Kong", "Taiwan"]', 1, '/flags/mo.svg', 'Bandeiras', 18, 'MO'),
('De que país é esta bandeira?', '["Síria", "Turquia", "Líciano", "Israel"]', 0, '/flags/sy.svg', 'Bandeiras', 18, 'SY'),
('De que país é esta bandeira?', '["Koweit", "Arábia Saudita", "Emirados Árabes Unidos", "Iraque"]', 0, '/flags/kw.svg', 'Bandeiras', 18, 'KW'),
('De que país é esta bandeira?', '["Qatar", "Emirados Árabes Unidos", "Arábia Saudita", "Koweit"]', 1, '/flags/qa.svg', 'Bandeiras', 18, 'QA'),
('De que país é esta bandeira?', '["Barém", "Arábia Saudita", "Qatar", "Koweit"]', 0, '/flags/bh.svg', 'Bandeiras', 18, 'BH'),
('De que país é esta bandeira?', '["Iémen", "Arábia Saudita", "Omã", "Djibouti"]', 0, '/flags/ye.svg', 'Bandeiras', 18, 'YE'),
('De que país é esta bandeira?', '["Líbia", "Egito", "Tunísia", "Argélia"]', 3, '/flags/dz.svg', 'Bandeiras', 18, 'DZ'),
('De que país é esta bandeira?', '["Nigéria", "Gana", "Camarões", "Guiné Equatorial"]', 3, '/flags/gq.svg', 'Bandeiras', 18, 'GQ'),
('De que país é esta bandeira?', '["Costa do Marfim", "Gana", "Burkina Faso", "Senegal"]', 3, '/flags/bf.svg', 'Bandeiras', 18, 'BF'),
('De que país é esta bandeira?', '["Libéria", "Serra Leoa", "Costa do Marfim", "Guiné"]', 2, '/flags/lr.svg', 'Bandeiras', 18, 'LR'),
('De que país é esta bandeira?', '["Marrocos", "Egito", "Argélia", "Tunísia"]', 3, '/flags/eg.svg', 'Bandeiras', 18, 'EG'),
('De que país é esta bandeira?', '["Nigéria", "Gabão", "Camarões", "República do Congo"]', 1, '/flags/cm.svg', 'Bandeiras', 18, 'CM'),
('De que país é esta bandeira?', '["Botswana", "África do Sul", "Zimbabwe", "Namíbia"]', 3, '/flags/na.svg', 'Bandeiras', 18, 'NA'),
('De que país é esta bandeira?', '["África do Sul", "Botswana", "Namíbia", "Angola"]', 2, '/flags/na.svg', 'Bandeiras', 18, 'NA'),
('De que país é esta bandeira?', '["Angola", "Moçambique", "Namíbia", "República do Congo"]', 1, '/flags/ao.svg', 'Bandeiras', 18, 'AO'),
('De que país é esta bandeira?', '["República do Congo", "República Democrática do Congo", "Angola", "Gabão"]', 2, '/flags/cg.svg', 'Bandeiras', 18, 'CG'),
('De que país é esta bandeira?', '["República Democrática do Congo", "República do Congo", "Uganda", "Ruanda"]', 0, '/flags/cd.svg', 'Bandeiras', 18, 'CD'),
('De que país é esta bandeira?', '["Camarões", "Nigéria", "Gabão", "República do Congo"]', 2, '/flags/cm.svg', 'Bandeiras', 18, 'CM'),
('De que país é esta bandeira?', '["Senegal", "Mauritânia", "Mali", "Guiné"]', 3, '/flags/gn.svg', 'Bandeiras', 18, 'GN'),
('De que país é esta bandeira?', '["Mali", "Senegal", "Burkina Faso", "Níger"]', 2, '/flags/bf.svg', 'Bandeiras', 18, 'BF'),
('De que país é esta bandeira?', '["Burkina Faso", "Mali", "Níger", "Benin"]', 1, '/flags/ne.svg', 'Bandeiras', 18, 'NE'),
('De que país é esta bandeira?', '["Níger", "Mali", "Burkina Faso", "Nigéria"]', 0, '/flags/ne.svg', 'Bandeiras', 18, 'NE'),
('De que país é esta bandeira?', '["Costa do Marfim", "Gana", "Burkina Faso", "Senegal"]', 1, '/flags/gh.svg', 'Bandeiras', 18, 'GH'),
('De que país é esta bandeira?', '["Guiné", "Senegal", "Mali", "Costa do Marfim"]', 2, '/flags/ml.svg', 'Bandeiras', 18, 'ML'),
('De que país é esta bandeira?', '["Serra Leoa", "Guiné", "Libéria", "Costa do Marfim"]', 1, '/flags/lr.svg', 'Bandeiras', 18, 'LR'),
('De que país é esta bandeira?', '["Togo", "Benin", "Gana", "Burkina Faso"]', 1, '/flags/tg.svg', 'Bandeiras', 18, 'TG'),
('De que país é esta bandeira?', '["Lesoto", "África do Sul", "Botswana", "Suazilândia"]', 2, '/flags/sz.svg', 'Bandeiras', 18, 'SZ'),
('De que país é esta bandeira?', '["Madagáscar", "Moçambique", "Maurícia", "Comores"]', 3, '/flags/km.svg', 'Bandeiras', 18, 'KM'),
('De que país é esta bandeira?', '["Maurícia", "Madagáscar", "Comores", "Seicheles"]', 2, '/flags/mg.svg', 'Bandeiras', 18, 'MG'),
('De que país é esta bandeira?', '["Seicheles", "Maurícia", "Madagáscar", "Comores"]', 1, '/flags/mu.svg', 'Bandeiras', 18, 'MU'),
('De que país é esta bandeira?', '["Comores", "Madagáscar", "Maurícia", "Seicheles"]', 3, '/flags/sc.svg', 'Bandeiras', 18, 'SC'),
('De que país é esta bandeira?', '["Somália", "Quénia", "Etiópia", "Djibouti"]', 0, '/flags/so.svg', 'Bandeiras', 18, 'SO'),
('De que país é esta bandeira?', '["Sudão", "Egito", "Etiópia", "Eritreia"]', 3, '/flags/sd.svg', 'Bandeiras', 18, 'SD'),
('De que país é esta bandeira?', '["Sudão do Sul", "Sudão", "Quénia", "Etiópia"]', 0, '/flags/ss.svg', 'Bandeiras', 18, 'SS'),
('De que país é esta bandeira?', '["Ilhas Marshall", "Micronésia", "Palau", "Quiribati"]', 1, '/flags/fm.svg', 'Bandeiras', 18, 'FM'),
('De que país é esta bandeira?', '["Micronésia", "Ilhas Marshall", "Palau", "Quiribati"]', 2, '/flags/mh.svg', 'Bandeiras', 18, 'MH'),
('De que país é esta bandeira?', '["Palau", "Micronésia", "Ilhas Marshall", "Filipinas"]', 0, '/flags/pw.svg', 'Bandeiras', 18, 'PW'),
('De que país é esta bandeira?', '["Vanuatu", "Fiji", "Nova Zelândia", "Austrália"]', 0, '/flags/vu.svg', 'Bandeiras', 18, 'VU'),
('De que país é esta bandeira?', '["Tuvalu", "Quiribati", "Fiji", "Nova Zelândia"]', 1, '/flags/ki.svg', 'Bandeiras', 18, 'KI'),
('De que país é esta bandeira?', '["Quiribati", "Fiji", "Samoa", "Nova Zelândia"]', 1, '/flags/tv.svg', 'Bandeiras', 18, 'TV'),
('De que país é esta bandeira?', '["Gibraltar", "Reino Unido", "Espanha", "Portugal"]', 0, '/flags/gi.svg', 'Bandeiras', 18, 'GI'),
('De que país é esta bandeira?', '["Santa Helena", "Reino Unido", "África do Sul", "Brasil"]', 0, '/flags/sh.svg', 'Bandeiras', 18, 'SH'),
('De que país é esta bandeira?', '["Reunião", "França", "Maurícia", "Madagáscar"]', 1, '/flags/re.svg', 'Bandeiras', 18, 'RE'),
('De que país é esta bandeira?', '["Mayotte", "Comores", "Madagáscar", "Reunião"]', 1, '/flags/yt.svg', 'Bandeiras', 18, 'YT'),
('De que país é esta bandeira?', '["Guernsey", "Reino Unido", "França", "Jersey"]', 2, '/flags/gg.svg', 'Bandeiras', 18, 'GG'),
('De que país é esta bandeira?', '["Ilhas Virgens Americanas", "Estados Unidos", "Porto Rico", "Ilhas Virgens Britânicas"]', 0, '/flags/vi.svg', 'Bandeiras', 18, 'VI'),
('De que país é esta bandeira?', '["Anguilla", "Reino Unido", "Ilhas Virgens Britânicas", "São Cristóvão e Nevis"]', 2, '/flags/ky.svg', 'Bandeiras', 18, 'KY'),
('De que país é esta bandeira?', '["Aruba", "Holanda", "Antilhas Holandesas", "Colômbia"]', 3, '/flags/cw.svg', 'Bandeiras', 18, 'CW'),
('De que país é esta bandeira?', '["Curaçao", "Venezuela", "Aruba", "Antilhas Holandesas"]', 1, '/flags/aw.svg', 'Bandeiras', 18, 'AW'),
('De que país é esta bandeira?', '["São Martinho", "Holanda", "França", "Antilhas Holandesas"]', 2, '/flags/mf.svg', 'Bandeiras', 18, 'MF'),
('De que país é esta bandeira?', '["Martinica", "França", "Guadalupe", "São Martinho"]', 0, '/flags/mq.svg', 'Bandeiras', 18, 'MQ'),
('De que país é esta bandeira?', '["Belize", "México", "Guatemala", "Honduras"]', 0, '/flags/bz.svg', 'Bandeiras', 18, 'BZ'),
('De que país é esta bandeira?', '["Nigéria", "Gana", "Costa do Marfim", "Senegal"]', 2, '/flags/sn.svg', 'Bandeiras', 18, 'SN'),
('De que país é esta bandeira?', '["Espanha", "França", "Portugal", "Andorra"]', 3, '/flags/ad.svg', 'Bandeiras', 18, 'AD'),
('De que país é esta bandeira?', '["Costa Rica", "Panamá", "Nicarágua", "Colômbia"]', 3, '/flags/co.svg', 'Bandeiras', 18, 'CO'),
('De que país é esta bandeira?', '["Colômbia", "Venezuela", "Equador", "Peru"]', 1, '/flags/ve.svg', 'Bandeiras', 18, 'VE'),
('De que país é esta bandeira?', '["Peru", "Chile", "Bolívia", "Equador"]', 2, '/flags/bo.svg', 'Bandeiras', 18, 'BO'),
('De que país é esta bandeira?', '["Venezuela", "Colômbia", "Brasil", "Peru"]', 0, '/flags/ve.svg', 'Bandeiras', 18, 'VE'),
('De que país é esta bandeira?', '["Haiti", "República Dominicana", "Cuba", "Jamaica"]', 3, '/flags/ht.svg', 'Bandeiras', 18, 'HT'),
('De que país é esta bandeira?', '["El Salvador", "Guatemala", "Honduras", "Nicarágua"]', 0, '/flags/sv.svg', 'Bandeiras', 18, 'SV'),
('De que país é esta bandeira?', '["Nicarágua", "Honduras", "Costa Rica", "El Salvador"]', 1, '/flags/ni.svg', 'Bandeiras', 18, 'NI'),
('De que país é esta bandeira?', '["Quirguistão", "Cazaquistão", "Uzbequistão", "Tajiquistão"]', 3, '/flags/kg.svg', 'Bandeiras', 18, 'KG'),
('De que país é esta bandeira?', '["Uzbequistão", "Cazaquistão", "Turquemenistão", "Quirguistão"]', 1, '/flags/kz.svg', 'Bandeiras', 18, 'KZ'),
('De que país é esta bandeira?', '["Arménia", "Azerbaijão", "Geórgia", "Rússia"]', 3, '/flags/am.svg', 'Bandeiras', 18, 'AM'),
('De que país é esta bandeira?', '["Ruanda", "Uganda", "Tanzânia", "Burundi"]', 3, '/flags/bi.svg', 'Bandeiras', 18, 'BI'),
('De que país é esta bandeira?', '["Zimbabwe", "Zâmbia", "Moçambique", "Botswana"]', 0, '/flags/zw.svg', 'Bandeiras', 18, 'ZW'),
('De que país é esta bandeira?', '["Namíbia", "África do Sul", "Botswana", "Angola"]', 1, '/flags/na.svg', 'Bandeiras', 18, 'NA'),
('De que país é esta bandeira?', '["Suazilândia", "África do Sul", "Moçambique", "Lesoto"]', 0, '/flags/sz.svg', 'Bandeiras', 18, 'SZ'),
('De que país é esta bandeira?', '["Togo", "Benin", "Gana", "Costa do Marfim"]', 2, '/flags/ci.svg', 'Bandeiras', 18, 'CI'),
('De que país é esta bandeira?', '["Gabão", "Camarões", "República do Congo", "Guiné Equatorial"]', 2, '/flags/gq.svg', 'Bandeiras', 18, 'GQ'),
('De que país é esta bandeira?', '["Nigéria", "Gana", "Camarões", "Guiné Equatorial"]', 3, '/flags/gq.svg', 'Bandeiras', 18, 'GQ'),
('De que país é esta bandeira?', '["Libéria", "Serra Leoa", "Costa do Marfim", "Guiné"]', 3, '/flags/gn.svg', 'Bandeiras', 18, 'GN'),
('De que país é esta bandeira?', '["Nigéria", "Gana", "Camarões", "Gabão"]', 2, '/flags/cm.svg', 'Bandeiras', 18, 'CM'),
('De que país é esta bandeira?', '["Marrocos", "Argélia", "Tunísia", "Egito"]', 0, '/flags/ma.svg', 'Bandeiras', 18, 'MA'),
('De que país é esta bandeira?', '["Nigéria", "Gabão", "Camarões", "República do Congo"]', 1, '/flags/ga.svg', 'Bandeiras', 18, 'GA')
ON CONFLICT DO NOTHING;
