#!/usr/bin/env python3
import random

flags = [
    ("pt", "Portugal", ["Portugal", "Espanha", "França", "Itália"]),
    ("es", "Espanha", ["Espanha", "Portugal", "México", "França"]),
    ("fr", "França", ["França", "Reino Unido", "Alemanha", "Bélgica"]),
    ("de", "Alemanha", ["Alemanha", "Bélgica", "Suíça", "Áustria"]),
    ("it", "Itália", ["Itália", "Espanha", "França", "Grécia"]),
    ("gb", "Reino Unido", ["Reino Unido", "Irlanda", "Austrália", "Nova Zelândia"]),
    ("nl", "Holanda", ["Holanda", "Bélgica", "Luxemburgo", "Dinamarca"]),
    ("be", "Bélgica", ["Bélgica", "Holanda", "Alemanha", "França"]),
    ("ch", "Suíça", ["Suíça", "Áustria", "Bélgica", "Liechtenstein"]),
    ("at", "Áustria", ["Áustria", "Suíça", "Alemanha", "Hungria"]),
    ("gr", "Grécia", ["Grécia", "Itália", "Chipre", "Albânia"]),
    ("se", "Suécia", ["Suécia", "Noruega", "Finlândia", "Dinamarca"]),
    ("no", "Noruega", ["Noruega", "Suécia", "Dinamarca", "Islândia"]),
    ("dk", "Dinamarca", ["Dinamarca", "Noruega", "Suécia", "Finlândia"]),
    ("fi", "Finlândia", ["Finlândia", "Suécia", "Noruega", "Estónia"]),
    ("ie", "Irlanda", ["Irlanda", "Reino Unido", "Escócia", "País de Gales"]),
    ("pl", "Polónia", ["Polónia", "Ucrânia", "República Checa", "Eslováquia"]),
    ("ua", "Ucrânia", ["Ucrânia", "Rússia", "Bielorrússia", "Moldávia"]),
    ("cz", "República Checa", ["República Checa", "Eslováquia", "Polónia", "Hungria"]),
    ("hu", "Hungria", ["Hungria", "Áustria", "Roménia", "Sérvia"]),
    ("ro", "Roménia", ["Roménia", "Hungria", "Moldávia", "Bulgária"]),
    ("bg", "Bulgária", ["Bulgária", "Roménia", "Grécia", "Sérvia"]),
    ("rs", "Sérvia", ["Sérvia", "Croácia", "Eslovénia", "Bósnia"]),
    ("hr", "Croácia", ["Croácia", "Sérvia", "Eslovénia", "Bósnia"]),
    ("si", "Eslovénia", ["Eslovénia", "Croácia", "Sérvia", "Eslováquia"]),
    ("sk", "Eslováquia", ["Eslováquia", "República Checa", "Eslovénia", "Polónia"]),
    ("br", "Brasil", ["Brasil", "Portugal", "Argentina", "Espanha"]),
    ("ar", "Argentina", ["Argentina", "Uruguai", "Paraguai", "Brasil"]),
    ("cl", "Chile", ["Chile", "Peru", "Equador", "Colômbia"]),
    ("co", "Colômbia", ["Colômbia", "Venezuela", "Equador", "Peru"]),
    ("pe", "Peru", ["Peru", "Chile", "Bolívia", "Equador"]),
    ("ve", "Venezuela", ["Venezuela", "Colômbia", "Brasil", "Peru"]),
    ("ec", "Equador", ["Equador", "Peru", "Colômbia", "Venezuela"]),
    ("bo", "Bolívia", ["Bolívia", "Peru", "Chile", "Paraguai"]),
    ("uy", "Uruguai", ["Uruguai", "Argentina", "Paraguai", "Brasil"]),
    ("py", "Paraguai", ["Paraguai", "Uruguai", "Argentina", "Bolívia"]),
    ("us", "Estados Unidos", ["Estados Unidos", "México", "Canadá", "Reino Unido"]),
    ("mx", "México", ["México", "Espanha", "Itália", "França"]),
    ("ca", "Canadá", ["Canadá", "Estados Unidos", "Reino Unido", "França"]),
    ("cu", "Cuba", ["Cuba", "Jamaica", "Haiti", "República Dominicana"]),
    ("jm", "Jamaica", ["Jamaica", "Cuba", "Haiti", "Trinidad e Tobago"]),
    ("jp", "Japão", ["Japão", "China", "Coreia do Sul", "Vietname"]),
    ("cn", "China", ["China", "Japão", "Índia", "Indonésia"]),
    ("kr", "Coreia do Sul", ["Coreia do Sul", "Japão", "China", "Singapura"]),
    ("in", "Índia", ["Índia", "Paquistão", "Bangladesh", "Sri Lanka"]),
    ("au", "Austrália", ["Austrália", "Nova Zelândia", "Reino Unido", "Fiji"]),
    ("th", "Tailândia", ["Tailândia", "Vietname", "Laos", "Camboja"]),
    ("vn", "Vietname", ["Vietname", "Tailândia", "Laos", "Camboja"]),
    ("id", "Indonésia", ["Indonésia", "Malásia", "Singapura", "Brunei"]),
    ("ph", "Filipinas", ["Filipinas", "Indonésia", "Malásia", "Singapura"]),
    ("sg", "Singapura", ["Singapura", "Malásia", "Indonésia", "Brunei"]),
    ("my", "Malásia", ["Malásia", "Indonésia", "Singapura", "Brunei"]),
    ("ru", "Rússia", ["Rússia", "Ucrânia", "Bielorrússia", "Cazaquistão"]),
    ("tr", "Turquia", ["Turquia", "Grécia", "Chipre", "Síria"]),
    ("ae", "Emirados Árabes Unidos", ["Emirados Árabes Unidos", "Arábia Saudita", "Qatar", "Koweit"]),
    ("sa", "Arábia Saudita", ["Arábia Saudita", "Emirados Árabes Unidos", "Qatar", "Omã"]),
    ("il", "Israel", ["Israel", "Palestina", "Líciano", "Jordânia"]),
    ("ir", "Irão", ["Irão", "Iraque", "Paquistão", "Afeganistão"]),
    ("iq", "Iraque", ["Iraque", "Irão", "Arábia Saudita", "Koweit"]),
    ("eg", "Egito", ["Egito", "Marrocos", "Argélia", "Tunísia"]),
    ("za", "África do Sul", ["África do Sul", "Nigéria", "Quénia", "Gana"]),
    ("ma", "Marrocos", ["Marrocos", "Egito", "Argélia", "Tunísia"]),
    ("ng", "Nigéria", ["Nigéria", "Gana", "Quénia", "Camarões"]),
    ("ke", "Quénia", ["Quénia", "Tanzânia", "Uganda", "Etiópia"]),
    ("gh", "Gana", ["Gana", "Nigéria", "Costa do Marfim", "Senegal"]),
    ("tz", "Tanzânia", ["Tanzânia", "Quénia", "Uganda", "Ruanda"]),
    ("tn", "Tunísia", ["Tunísia", "Argélia", "Marrocos", "Líbia"]),
    ("dz", "Argélia", ["Argélia", "Tunísia", "Marrocos", "Líbia"]),
    ("et", "Etiópia", ["Etiópia", "Quénia", "Somália", "Eritreia"]),
    ("nz", "Nova Zelândia", ["Nova Zelândia", "Austrália", "Fiji", "Reino Unido"]),
    ("fj", "Fiji", ["Fiji", "Samoa", "Tonga", "Papua Nova Guiné"]),
    ("pg", "Papua Nova Guiné", ["Papua Nova Guiné", "Austrália", "Fiji", "Indonésia"]),
    ("tw", "Taiwan", ["Taiwan", "China", "Japão", "Coreia do Sul"]),
    ("kz", "Cazaquistão", ["Cazaquistão", "Uzbequistão", "Turquemenistão", "Quirguistão"]),
    ("by", "Bielorrússia", ["Bielorrússia", "Ucrânia", "Rússia", "Moldávia"]),
    ("ee", "Estónia", ["Estónia", "Letónia", "Lituânia", "Rússia"]),
    ("lv", "Letónia", ["Letónia", "Estónia", "Lituânia", "Polónia"]),
    ("lt", "Lituânia", ["Lituânia", "Letónia", "Estónia", "Polónia"]),
    ("mt", "Malta", ["Malta", "Chipre", "Itália", "Grécia"]),
    ("cy", "Chipre", ["Chipre", "Grécia", "Turquia", "Malta"]),
    ("is", "Islândia", ["Islândia", "Noruega", "Finlândia", "Groenlândia"]),
    ("al", "Albânia", ["Albânia", "Grécia", "Itália", "Macedónia"]),
    ("ba", "Bósnia-Herzegovina", ["Bósnia-Herzegovina", "Croácia", "Sérvia", "Montenegro"]),
    ("mk", "Macedónia do Norte", ["Macedónia do Norte", "Grécia", "Albânia", "Bulgária"]),
    ("me", "Montenegro", ["Montenegro", "Sérvia", "Croácia", "Albânia"]),
    ("lu", "Luxemburgo", ["Luxemburgo", "Bélgica", "Holanda", "França"]),
    ("li", "Liechtenstein", ["Liechtenstein", "Suíça", "Áustria", "Alemanha"]),
    ("mc", "Mónaco", ["Mónaco", "França", "Itália", "Espanha"]),
    ("sm", "San Marino", ["San Marino", "Itália", "Vaticano", "França"]),
    ("va", "Vaticano", ["Vaticano", "Itália", "Mónaco", "Espanha"]),
    ("ad", "Andorra", ["Andorra", "Espanha", "França", "Portugal"]),
    ("md", "Moldávia", ["Moldávia", "Roménia", "Ucrânia", "Rússia"]),
    ("hn", "Honduras", ["Honduras", "Guatemala", "El Salvador", "Nicarágua"]),
    ("sv", "El Salvador", ["El Salvador", "Guatemala", "Honduras", "Nicarágua"]),
    ("ni", "Nicarágua", ["Nicarágua", "Honduras", "Costa Rica", "El Salvador"]),
    ("do", "República Dominicana", ["República Dominicana", "Cuba", "Haiti", "Porto Rico"]),
    ("ht", "Haiti", ["Haiti", "República Dominicana", "Cuba", "Jamaica"]),
    ("pr", "Porto Rico", ["Porto Rico", "Estados Unidos", "República Dominicana", "Cuba"]),
    ("tt", "Trinidad e Tobago", ["Trinidad e Tobago", "Jamaica", "Barbados", "Bahamas"]),
    ("bb", "Barbados", ["Barbados", "Trinidad e Tobago", "Jamaica", "Bahamas"]),
    ("bs", "Bahamas", ["Bahamas", "Cuba", "Jamaica", "Porto Rico"]),
    ("bz", "Belize", ["Belize", "México", "Guatemala", "Honduras"]),
    ("cr", "Costa Rica", ["Costa Rica", "Panamá", "Nicarágua", "Honduras"]),
    ("pa", "Panamá", ["Panamá", "Costa Rica", "Nicarágua", "Colômbia"]),
    ("gt", "Guatemala", ["Guatemala", "Honduras", "El Salvador", "Nicarágua"]),
    ("np", "Nepal", ["Nepal", "Índia", "China", "Butão"]),
    ("bt", "Butão", ["Butão", "Índia", "China", "Nepal"]),
    ("la", "Laos", ["Laos", "Tailândia", "Vietname", "Camboja"]),
    ("kh", "Camboja", ["Camboja", "Tailândia", "Vietname", "Laos"]),
    ("bn", "Brunei", ["Brunei", "Malásia", "Indonésia", "Singapura"]),
    ("hk", "Hong Kong", ["Hong Kong", "China", "Japão", "Singapura"]),
    ("mo", "Macau", ["Macau", "China", "Hong Kong", "Taiwan"]),
    ("mn", "Mongólia", ["Mongólia", "Rússia", "China", "Cazaquistão"]),
    ("sy", "Síria", ["Síria", "Turquia", "Líciano", "Israel"]),
    ("jo", "Jordânia", ["Jordânia", "Israel", "Síria", "Iraque"]),
    ("lb", "Líciano", ["Líciano", "Israel", "Jordânia", "Síria"]),
    ("kw", "Koweit", ["Koweit", "Arábia Saudita", "Emirados Árabes Unidos", "Iraque"]),
    ("qa", "Qatar", ["Qatar", "Emirados Árabes Unidos", "Arábia Saudita", "Koweit"]),
    ("bh", "Barém", ["Barém", "Arábia Saudita", "Qatar", "Koweit"]),
    ("om", "Omã", ["Omã", "Arábia Saudita", "Emirados Árabes Unidos", "Iémen"]),
    ("ye", "Iémen", ["Iémen", "Arábia Saudita", "Omã", "Djibouti"]),
    ("uz", "Uzbequistão", ["Uzbequistão", "Cazaquistão", "Turquemenistão", "Quirguistão"]),
    ("kg", "Quirguistão", ["Quirguistão", "Cazaquistão", "Uzbequistão", "Tajiquistão"]),
    ("tj", "Tajiquistão", ["Tajiquistão", "Uzbequistão", "Afeganistão", "China"]),
    ("tm", "Turquemenistão", ["Turquemenistão", "Cazaquistão", "Irão", "Afeganistão"]),
    ("am", "Arménia", ["Arménia", "Azerbaijão", "Geórgia", "Rússia"]),
    ("az", "Azerbaijão", ["Azerbaijão", "Arménia", "Rússia", "Irão"]),
    ("ge", "Geórgia", ["Geórgia", "Rússia", "Turquia", "Azerbaijão"]),
    ("ly", "Líbia", ["Líbia", "Egito", "Tunísia", "Argélia"]),
    ("sd", "Sudão", ["Sudão", "Egipto", "Etiiópia", "Eritreia"]),
    ("so", "Somália", ["Somália", "Quénia", "Etiópia", "Djibouti"]),
    ("ug", "Uganda", ["Uganda", "Quénia", "Tanzânia", "Ruanda"]),
    ("rw", "Ruanda", ["Ruanda", "Uganda", "Tanzânia", "Burundi"]),
    ("bi", "Burundi", ["Burundi", "Ruanda", "Uganda", "Tanzânia"]),
    ("mz", "Moçambique", ["Moçambique", "Tanzânia", "Zâmbia", "Zimbabwe"]),
    ("zw", "Zimbabwe", ["Zimbabwe", "Zâmbia", "Moçambique", "Botswana"]),
    ("zm", "Zâmbia", ["Zâmbia", "Zimbabwe", "Moçambique", "Malawi"]),
    ("mw", "Malawi", ["Malawi", "Moçambique", "Zâmbia", "Tanzânia"]),
    ("bw", "Botswana", ["Botswana", "África do Sul", "Zimbabwe", "Namíbia"]),
    ("na", "Namíbia", ["Namíbia", "África do Sul", "Botswana", "Angola"]),
    ("ao", "Angola", ["Angola", "Moçambique", "Namíbia", "República do Congo"]),
    ("cg", "República do Congo", ["República do Congo", "República Democrática do Congo", "Angola", "Gabão"]),
    ("cd", "República Democrática do Congo", ["República Democrática do Congo", "República do Congo", "Uganda", "Ruanda"]),
    ("cm", "Camarões", ["Camarões", "Nigéria", "Gabão", "República do Congo"]),
    ("ga", "Gabão", ["Gabão", "Camarões", "República do Congo", "Guiné Equatorial"]),
    ("sn", "Senegal", ["Senegal", "Mauritânia", "Mali", "Guiné"]),
    ("ml", "Mali", ["Mali", "Senegal", "Burkina Faso", "Níger"]),
    ("bf", "Burkina Faso", ["Burkina Faso", "Mali", "Níger", "Benin"]),
    ("ne", "Níger", ["Níger", "Mali", "Burkina Faso", "Nigéria"]),
    ("ci", "Costa do Marfim", ["Costa do Marfim", "Gana", "Burkina Faso", "Senegal"]),
    ("gn", "Guiné", ["Guiné", "Senegal", "Mali", "Costa do Marfim"]),
    ("sl", "Serra Leoa", ["Serra Leoa", "Guiné", "Libéria", "Costa do Marfim"]),
    ("lr", "Libéria", ["Libéria", "Serra Leoa", "Costa do Marfim", "Guiné"]),
    ("mr", "Mauritânia", ["Mauritânia", "Senegal", "Mali", "Marrocos"]),
    ("bj", "Benin", ["Benin", "Nigéria", "Burkina Faso", "Togo"]),
    ("tg", "Togo", ["Togo", "Benin", "Gana", "Burkina Faso"]),
    ("gm", "Gâmbia", ["Gâmbia", "Senegal", "Guiné", "Mauritânia"]),
    ("gw", "Guiné-Bissau", ["Guiné-Bissau", "Senegal", "Guiné", "Gâmbia"]),
    ("ls", "Lesoto", ["Lesoto", "África do Sul", "Botswana", "Suazilândia"]),
    ("sz", "Suazilândia", ["Suazilândia", "África do Sul", "Moçambique", "Lesoto"]),
    ("mg", "Madagáscar", ["Madagáscar", "Moçambique", "Maurícia", "Comores"]),
    ("mu", "Maurícia", ["Maurícia", "Madagáscar", "Comores", "Seicheles"]),
    ("sc", "Seicheles", ["Seicheles", "Maurícia", "Madagáscar", "Comores"]),
    ("km", "Comores", ["Comores", "Madagáscar", "Maurícia", "Seicheles"]),
    ("dj", "Djibouti", ["Djibouti", "Etiópia", "Eritreia", "Somália"]),
    ("er", "Eritreia", ["Eritreia", "Etiópia", "Djibouti", "Sudão"]),
    ("cf", "República Centro-Africana", ["República Centro-Africana", "Chade", "Camarões", "Congo"]),
    ("td", "Chade", ["Chade", "República Centro-Africana", "Sudão", "Líbia"]),
    ("ss", "Sudão do Sul", ["Sudão do Sul", "Sudão", "Quénia", "Etiópia"]),
    ("gq", "Guiné Equatorial", ["Guiné Equatorial", "Gabão", "Camarões", "República do Congo"]),
    ("cv", "Cabo Verde", ["Cabo Verde", "Senegal", "Guiné-Bissau", "Mauritânia"]),
    ("st", "São Tomé e Príncipe", ["São Tomé e Príncipe", "Gabão", "Nigéria", "Guiné Equatorial"]),
    ("mv", "Maldivas", ["Maldivas", "Índia", "Sri Lanka", "Indonésia"]),
    ("ws", "Samoa", ["Samoa", "Fiji", "Tonga", "Nova Zelândia"]),
    ("to", "Tonga", ["Tonga", "Fiji", "Samoa", "Nova Zelândia"]),
    ("ki", "Quiribati", ["Quiribati", "Fiji", "Samoa", "Nova Zelândia"]),
    ("mh", "Ilhas Marshall", ["Ilhas Marshall", "Micronésia", "Palau", "Quiribati"]),
    ("fm", "Micronésia", ["Micronésia", "Ilhas Marshall", "Palau", "Quiribati"]),
    ("pw", "Palau", ["Palau", "Micronésia", "Ilhas Marshall", "Filipinas"]),
    ("vu", "Vanuatu", ["Vanuatu", "Fiji", "Nova Zelândia", "Austrália"]),
    ("sb", "Ilhas Salomão", ["Ilhas Salomão", "Papua Nova Guiné", "Fiji", "Austrália"]),
    ("nr", "Nauru", ["Nauru", "Quiribati", "Austrália", "Nova Zelândia"]),
    ("tv", "Tuvalu", ["Tuvalu", "Quiribati", "Fiji", "Nova Zelândia"]),
    ("nc", "Nova Caledónia", ["Nova Caledónia", "Austrália", "Fiji", "Vanuatu"]),
    ("pf", "Polinésia Francesa", ["Polinésia Francesa", "Nova Zelândia", "Austrália", "Hawai"]),
    ("tl", "Timor-Leste", ["Timor-Leste", "Indonésia", "Portugal", "Austrália"]),
    ("xk", "Kosovo", ["Kosovo", "Albânia", "Sérvia", "Montenegro"]),
    ("gl", "Gronelândia", ["Gronelândia", "Canadá", "Dinamarca", "Islândia"]),
    ("fo", "Ilhas Faroé", ["Ilhas Faroé", "Dinamarca", "Islândia", "Noruega"]),
    ("gu", "Guam", ["Guam", "Estados Unidos", "Filipinas", "Austrália"]),
    ("vi", "Ilhas Virgens Americanas", ["Ilhas Virgens Americanas", "Estados Unidos", "Porto Rico", "Ilhas Virgens Britânicas"]),
    ("vg", "Ilhas Virgens Britânicas", ["Ilhas Virgens Britânicas", "Porto Rico", "Ilhas Caimão", "Anguilla"]),
    ("bm", "Bermudas", ["Bermudas", "Reino Unido", "Canadá", "Estados Unidos"]),
    ("ai", "Anguilla", ["Anguilla", "Reino Unido", "Ilhas Virgens Britânicas", "São Cristóvão e Nevis"]),
    ("ky", "Ilhas Caimão", ["Ilhas Caimão", "Jamaica", "Ilhas Virgens Britânicas", "Cuba"]),
    ("aw", "Aruba", ["Aruba", "Holanda", "Antilhas Holandesas", "Colômbia"]),
    ("cw", "Curaçao", ["Curaçao", "Venezuela", "Aruba", "Antilhas Holandesas"]),
    ("mf", "São Martinho", ["São Martinho", "Holanda", "França", "Antilhas Holandesas"]),
    ("bl", "São Bartolomeu", ["São Bartolomeu", "França", "Guadalupe", "Martinica"]),
    ("mq", "Martinica", ["Martinica", "França", "Guadalupe", "São Martinho"]),
    ("gp", "Guadalupe", ["Guadalupe", "França", "Martinica", "São Martinho"]),
    ("re", "Reunião", ["Reunião", "França", "Maurícia", "Madagáscar"]),
    ("yt", "Mayotte", ["Mayotte", "Comores", "Madagáscar", "Reunião"]),
    ("je", "Jersey", ["Jersey", "Reino Unido", "França", "Guernsey"]),
    ("gg", "Guernsey", ["Guernsey", "Reino Unido", "França", "Jersey"]),
    ("im", "Ilha de Man", ["Ilha de Man", "Reino Unido", "Irlanda", "Escócia"]),
    ("gi", "Gibraltar", ["Gibraltar", "Reino Unido", "Espanha", "Portugal"]),
    ("sh", "Santa Helena", ["Santa Helena", "Reino Unido", "África do Sul", "Brasil"]),
    ("pk", "Paquistão", ["Paquistão", "Índia", "Afeganistão", "Bangladesh"]),
    ("bd", "Bangladesh", ["Bangladesh", "Índia", "Mianmar", "Sri Lanka"]),
    ("mm", "Mianmar", ["Mianmar", "Tailândia", "Laos", "Bangladesh"]),
    ("lk", "Sri Lanka", ["Sri Lanka", "Índia", "Paquistão", "Bangladesh"]),
]

# Embaralhar as bandeiras
random.shuffle(flags)

print("-- SQL COMPLETO: TODAS AS BANDEIRAS COM RESPOSTAS RANDOMIZADAS")
print("-- Executar no SQL Editor do Supabase Dashboard")
print("")
print("INSERT INTO questions (text, options, correct_option, image_url, category, age_rating, country_code) VALUES")

values = []
for i, (code, country, options) in enumerate(flags):
    # Encontrar índice da resposta correta
    correct_idx = options.index(country)
    
    # Embaralhar opções
    shuffled = options.copy()
    random.shuffle(shuffled)
    
    # Encontrar novo índice da resposta correta após baralhar
    new_correct_idx = shuffled.index(country)
    
    # Formatar options como JSON
    options_str = '["' + '", "'.join(shuffled) + '"]'
    
    values.append(f"('De que país é esta bandeira?', '{options_str}', {new_correct_idx}, '/flags/{code}.svg', 'Bandeiras', 18, '{code.upper()}')")

print(',\n'.join(values))
print("")
print("ON CONFLICT DO NOTHING;")
