-- SQL COMPLETO: TODAS AS BANDEIRAS COM RESPOSTAS RANDOMIZADAS
-- Executar no SQL Editor do Supabase Dashboard

INSERT INTO questions (text, options, correct_option, image_url, category, age_rating, country_code) VALUES
('De que país é esta bandeira?', '["Reino Unido", "Guernsey", "França", "Jersey"]', 1, '/flags/gg.svg', 'Bandeiras', 18, 'GG'),
('De que país é esta bandeira?', '["Laos", "Tailândia", "Bangladesh", "Mianmar"]', 3, '/flags/mm.svg', 'Bandeiras', 18, 'MM'),
('De que país é esta bandeira?', '["Maurícia", "Moçambique", "Madagáscar", "Comores"]', 2, '/flags/mg.svg', 'Bandeiras', 18, 'MG'),
('De que país é esta bandeira?', '["Ilhas Caimão", "Ilhas Virgens Britânicas", "Jamaica", "Cuba"]', 0, '/flags/ky.svg', 'Bandeiras', 18, 'KY'),
('De que país é esta bandeira?', '["Austrália", "Nova Zelândia", "Nauru", "Quiribati"]', 2, '/flags/nr.svg', 'Bandeiras', 18, 'NR'),
('De que país é esta bandeira?', '["Quénia", "Camarões", "Nigéria", "Gana"]', 2, '/flags/ng.svg', 'Bandeiras', 18, 'NG'),
('De que país é esta bandeira?', '["Angola", "Botswana", "Namíbia", "África do Sul"]', 2, '/flags/na.svg', 'Bandeiras', 18, 'NA'),
('De que país é esta bandeira?', '["Síria", "Jordânia", "Líciano", "Israel"]', 2, '/flags/lb.svg', 'Bandeiras', 18, 'LB'),
('De que país é esta bandeira?', '["Marrocos", "Tunísia", "Argélia", "Líbia"]', 2, '/flags/dz.svg', 'Bandeiras', 18, 'DZ'),
('De que país é esta bandeira?', '["Quénia", "Sudão", "Etiópia", "Sudão do Sul"]', 3, '/flags/ss.svg', 'Bandeiras', 18, 'SS'),
('De que país é esta bandeira?', '["Itália", "Espanha", "México", "França"]', 2, '/flags/mx.svg', 'Bandeiras', 18, 'MX'),
('De que país é esta bandeira?', '["Trinidad e Tobago", "Haiti", "Jamaica", "Cuba"]', 2, '/flags/jm.svg', 'Bandeiras', 18, 'JM'),
('De que país é esta bandeira?', '["Bangladesh", "Paquistão", "Sri Lanka", "Índia"]', 2, '/flags/lk.svg', 'Bandeiras', 18, 'LK'),
('De que país é esta bandeira?', '["Marrocos", "Tunísia", "Argélia", "Líbia"]', 1, '/flags/tn.svg', 'Bandeiras', 18, 'TN'),
('De que país é esta bandeira?', '["Sudão", "Líbia", "Chade", "República Centro-Africana"]', 2, '/flags/td.svg', 'Bandeiras', 18, 'TD'),
('De que país é esta bandeira?', '["Coreia do Sul", "Japão", "Taiwan", "China"]', 2, '/flags/tw.svg', 'Bandeiras', 18, 'TW'),
('De que país é esta bandeira?', '["Tailândia", "Camboja", "Laos", "Vietname"]', 0, '/flags/th.svg', 'Bandeiras', 18, 'TH'),
('De que país é esta bandeira?', '["Polónia", "Estónia", "Letónia", "Lituânia"]', 3, '/flags/lt.svg', 'Bandeiras', 18, 'LT'),
('De que país é esta bandeira?', '["Espanha", "Portugal", "França", "Andorra"]', 3, '/flags/ad.svg', 'Bandeiras', 18, 'AD'),
('De que país é esta bandeira?', '["Palau", "Ilhas Marshall", "Quiribati", "Micronésia"]', 1, '/flags/mh.svg', 'Bandeiras', 18, 'MH'),
('De que país é esta bandeira?', '["Haiti", "Cuba", "República Dominicana", "Jamaica"]', 0, '/flags/ht.svg', 'Bandeiras', 18, 'HT'),
('De que país é esta bandeira?', '["Cazaquistão", "Irão", "Afeganistão", "Turquemenistão"]', 3, '/flags/tm.svg', 'Bandeiras', 18, 'TM'),
('De que país é esta bandeira?', '["Grécia", "Sérvia", "Bulgária", "Roménia"]', 2, '/flags/bg.svg', 'Bandeiras', 18, 'BG'),
('De que país é esta bandeira?', '["Liechtenstein", "Suíça", "Áustria", "Bélgica"]', 1, '/flags/ch.svg', 'Bandeiras', 18, 'CH'),
('De que país é esta bandeira?', '["Ilhas Virgens Americanas", "Ilhas Virgens Britânicas", "Porto Rico", "Estados Unidos"]', 0, '/flags/vi.svg', 'Bandeiras', 18, 'VI'),
('De que país é esta bandeira?', '["Guiné Equatorial", "Camarões", "Gabão", "República do Congo"]', 0, '/flags/gq.svg', 'Bandeiras', 18, 'GQ'),
('De que país é esta bandeira?', '["Nigéria", "Senegal", "Costa do Marfim", "Gana"]', 3, '/flags/gh.svg', 'Bandeiras', 18, 'GH'),
('De que país é esta bandeira?', '["Turquemenistão", "Uzbequistão", "Quirguistão", "Cazaquistão"]', 1, '/flags/uz.svg', 'Bandeiras', 18, 'UZ'),
('De que país é esta bandeira?', '["Mónaco", "Itália", "Espanha", "Vaticano"]', 3, '/flags/va.svg', 'Bandeiras', 18, 'VA'),
('De que país é esta bandeira?', '["Suíça", "Alemanha", "Áustria", "Bélgica"]', 1, '/flags/de.svg', 'Bandeiras', 18, 'DE'),
('De que país é esta bandeira?', '["Chade", "Congo", "Camarões", "República Centro-Africana"]', 3, '/flags/cf.svg', 'Bandeiras', 18, 'CF'),
('De que país é esta bandeira?', '["Brasil", "Argentina", "Portugal", "Espanha"]', 0, '/flags/br.svg', 'Bandeiras', 18, 'BR'),
('De que país é esta bandeira?', '["Holanda", "Bélgica", "França", "Alemanha"]', 1, '/flags/be.svg', 'Bandeiras', 18, 'BE'),
('De que país é esta bandeira?', '["Sri Lanka", "Índia", "Bangladesh", "Paquistão"]', 1, '/flags/in.svg', 'Bandeiras', 18, 'IN'),
('De que país é esta bandeira?', '["Zâmbia", "Zimbabwe", "Moçambique", "Tanzânia"]', 2, '/flags/mz.svg', 'Bandeiras', 18, 'MZ'),
('De que país é esta bandeira?', '["Afeganistão", "Tajiquistão", "China", "Uzbequistão"]', 1, '/flags/tj.svg', 'Bandeiras', 18, 'TJ'),
('De que país é esta bandeira?', '["Omã", "Iémen", "Emirados Árabes Unidos", "Arábia Saudita"]', 0, '/flags/om.svg', 'Bandeiras', 18, 'OM'),
('De que país é esta bandeira?', '["Rússia", "Arménia", "Azerbaijão", "Geórgia"]', 1, '/flags/am.svg', 'Bandeiras', 18, 'AM'),
('De que país é esta bandeira?', '["Estónia", "Suécia", "Noruega", "Finlândia"]', 3, '/flags/fi.svg', 'Bandeiras', 18, 'FI'),
('De que país é esta bandeira?', '["França", "Portugal", "México", "Espanha"]', 3, '/flags/es.svg', 'Bandeiras', 18, 'ES'),
('De que país é esta bandeira?', '["Burkina Faso", "Togo", "Benin", "Nigéria"]', 2, '/flags/bj.svg', 'Bandeiras', 18, 'BJ'),
('De que país é esta bandeira?', '["Tajiquistão", "Quirguistão", "Cazaquistão", "Uzbequistão"]', 1, '/flags/kg.svg', 'Bandeiras', 18, 'KG'),
('De que país é esta bandeira?', '["Arábia Saudita", "Qatar", "Koweit", "Barém"]', 3, '/flags/bh.svg', 'Bandeiras', 18, 'BH'),
('De que país é esta bandeira?', '["Reino Unido", "Fiji", "Nova Zelândia", "Austrália"]', 3, '/flags/au.svg', 'Bandeiras', 18, 'AU'),
('De que país é esta bandeira?', '["Estados Unidos", "Porto Rico", "Cuba", "República Dominicana"]', 1, '/flags/pr.svg', 'Bandeiras', 18, 'PR'),
('De que país é esta bandeira?', '["Taiwan", "Hong Kong", "China", "Macau"]', 3, '/flags/mo.svg', 'Bandeiras', 18, 'MO'),
('De que país é esta bandeira?', '["México", "Estados Unidos", "Reino Unido", "Canadá"]', 1, '/flags/us.svg', 'Bandeiras', 18, 'US'),
('De que país é esta bandeira?', '["Iraque", "Irão", "Arábia Saudita", "Koweit"]', 0, '/flags/iq.svg', 'Bandeiras', 18, 'IQ'),
('De que país é esta bandeira?', '["Maurícia", "Madagáscar", "Seicheles", "Comores"]', 2, '/flags/sc.svg', 'Bandeiras', 18, 'SC'),
('De que país é esta bandeira?', '["França", "Guadalupe", "São Bartolomeu", "Martinica"]', 2, '/flags/bl.svg', 'Bandeiras', 18, 'BL'),
('De que país é esta bandeira?', '["Índia", "Indonésia", "China", "Japão"]', 2, '/flags/cn.svg', 'Bandeiras', 18, 'CN'),
('De que país é esta bandeira?', '["Ruanda", "Tanzânia", "Uganda", "Burundi"]', 0, '/flags/rw.svg', 'Bandeiras', 18, 'RW'),
('De que país é esta bandeira?', '["Mali", "Guiné", "Senegal", "Costa do Marfim"]', 1, '/flags/gn.svg', 'Bandeiras', 18, 'GN'),
('De que país é esta bandeira?', '["Vanuatu", "Nova Zelândia", "Austrália", "Fiji"]', 0, '/flags/vu.svg', 'Bandeiras', 18, 'VU'),
('De que país é esta bandeira?', '["Suazilândia", "Moçambique", "Lesoto", "África do Sul"]', 0, '/flags/sz.svg', 'Bandeiras', 18, 'SZ'),
('De que país é esta bandeira?', '["Dinamarca", "Noruega", "Suécia", "Finlândia"]', 2, '/flags/se.svg', 'Bandeiras', 18, 'SE'),
('De que país é esta bandeira?', '["Brasil", "Uruguai", "Argentina", "Paraguai"]', 1, '/flags/uy.svg', 'Bandeiras', 18, 'UY'),
('De que país é esta bandeira?', '["Malawi", "Zâmbia", "Tanzânia", "Moçambique"]', 0, '/flags/mw.svg', 'Bandeiras', 18, 'MW'),
('De que país é esta bandeira?', '["Malta", "Grécia", "Turquia", "Chipre"]', 3, '/flags/cy.svg', 'Bandeiras', 18, 'CY'),
('De que país é esta bandeira?', '["Burkina Faso", "Gana", "Senegal", "Costa do Marfim"]', 3, '/flags/ci.svg', 'Bandeiras', 18, 'CI'),
('De que país é esta bandeira?', '["Líciano", "Turquia", "Israel", "Síria"]', 3, '/flags/sy.svg', 'Bandeiras', 18, 'SY'),
('De que país é esta bandeira?', '["Níger", "Burkina Faso", "Nigéria", "Mali"]', 0, '/flags/ne.svg', 'Bandeiras', 18, 'NE'),
('De que país é esta bandeira?', '["Honduras", "El Salvador", "Nicarágua", "Costa Rica"]', 2, '/flags/ni.svg', 'Bandeiras', 18, 'NI'),
('De que país é esta bandeira?', '["Uruguai", "Brasil", "Argentina", "Paraguai"]', 2, '/flags/ar.svg', 'Bandeiras', 18, 'AR'),
('De que país é esta bandeira?', '["Gâmbia", "Guiné", "Guiné-Bissau", "Senegal"]', 2, '/flags/gw.svg', 'Bandeiras', 18, 'GW'),
('De que país é esta bandeira?', '["Seicheles", "Madagáscar", "Comores", "Maurícia"]', 2, '/flags/km.svg', 'Bandeiras', 18, 'KM'),
('De que país é esta bandeira?', '["Croácia", "Sérvia", "Eslováquia", "Eslovénia"]', 3, '/flags/si.svg', 'Bandeiras', 18, 'SI'),
('De que país é esta bandeira?', '["Nova Zelândia", "Fiji", "Austrália", "Reino Unido"]', 0, '/flags/nz.svg', 'Bandeiras', 18, 'NZ'),
('De que país é esta bandeira?', '["República do Congo", "Camarões", "Gabão", "Nigéria"]', 1, '/flags/cm.svg', 'Bandeiras', 18, 'CM'),
('De que país é esta bandeira?', '["Honduras", "Costa Rica", "Nicarágua", "Panamá"]', 1, '/flags/cr.svg', 'Bandeiras', 18, 'CR'),
('De que país é esta bandeira?', '["Martinica", "França", "Guadalupe", "São Martinho"]', 0, '/flags/mq.svg', 'Bandeiras', 18, 'MQ'),
('De que país é esta bandeira?', '["Montenegro", "Croácia", "Albânia", "Sérvia"]', 0, '/flags/me.svg', 'Bandeiras', 18, 'ME'),
('De que país é esta bandeira?', '["Djibouti", "Eritreia", "Sudão", "Etiópia"]', 1, '/flags/er.svg', 'Bandeiras', 18, 'ER'),
('De que país é esta bandeira?', '["Uganda", "Tanzânia", "Ruanda", "Burundi"]', 3, '/flags/bi.svg', 'Bandeiras', 18, 'BI'),
('De que país é esta bandeira?', '["Peru", "Equador", "Colômbia", "Chile"]', 3, '/flags/cl.svg', 'Bandeiras', 18, 'CL'),
('De que país é esta bandeira?', '["Somália", "Quénia", "Etiópia", "Djibouti"]', 0, '/flags/so.svg', 'Bandeiras', 18, 'SO'),
('De que país é esta bandeira?', '["Mayotte", "Reunião", "Madagáscar", "Comores"]', 0, '/flags/yt.svg', 'Bandeiras', 18, 'YT'),
('De que país é esta bandeira?', '["Liechtenstein", "Áustria", "Alemanha", "Suíça"]', 0, '/flags/li.svg', 'Bandeiras', 18, 'LI'),
('De que país é esta bandeira?', '["Micronésia", "Palau", "Filipinas", "Ilhas Marshall"]', 1, '/flags/pw.svg', 'Bandeiras', 18, 'PW'),
('De que país é esta bandeira?', '["Papua Nova Guiné", "Fiji", "Austrália", "Indonésia"]', 0, '/flags/pg.svg', 'Bandeiras', 18, 'PG'),
('De que país é esta bandeira?', '["Rússia", "Moldávia", "Ucrânia", "Bielorrússia"]', 3, '/flags/by.svg', 'Bandeiras', 18, 'BY'),
('De que país é esta bandeira?', '["Quénia", "Somália", "Eritreia", "Etiópia"]', 3, '/flags/et.svg', 'Bandeiras', 18, 'ET'),
('De que país é esta bandeira?', '["Gronelândia", "Islândia", "Canadá", "Dinamarca"]', 0, '/flags/gl.svg', 'Bandeiras', 18, 'GL'),
('De que país é esta bandeira?', '["Argélia", "Egito", "Líbia", "Tunísia"]', 2, '/flags/ly.svg', 'Bandeiras', 18, 'LY'),
('De que país é esta bandeira?', '["Peru", "Venezuela", "Colômbia", "Equador"]', 3, '/flags/ec.svg', 'Bandeiras', 18, 'EC'),
('De que país é esta bandeira?', '["Palau", "Micronésia", "Ilhas Marshall", "Quiribati"]', 1, '/flags/fm.svg', 'Bandeiras', 18, 'FM'),
('De que país é esta bandeira?', '["Paquistão", "Bangladesh", "Afeganistão", "Índia"]', 0, '/flags/pk.svg', 'Bandeiras', 18, 'PK'),
('De que país é esta bandeira?', '["Guiné", "Costa do Marfim", "Serra Leoa", "Libéria"]', 2, '/flags/sl.svg', 'Bandeiras', 18, 'SL'),
('De que país é esta bandeira?', '["Mónaco", "França", "Espanha", "Itália"]', 0, '/flags/mc.svg', 'Bandeiras', 18, 'MC'),
('De que país é esta bandeira?', '["Noruega", "Ilhas Faroé", "Dinamarca", "Islândia"]', 1, '/flags/fo.svg', 'Bandeiras', 18, 'FO'),
('De que país é esta bandeira?', '["Sérvia", "Roménia", "Áustria", "Hungria"]', 3, '/flags/hu.svg', 'Bandeiras', 18, 'HU'),
('De que país é esta bandeira?', '["Uganda", "Etiópia", "Tanzânia", "Quénia"]', 3, '/flags/ke.svg', 'Bandeiras', 18, 'KE'),
('De que país é esta bandeira?', '["Mauritânia", "Cabo Verde", "Senegal", "Guiné-Bissau"]', 1, '/flags/cv.svg', 'Bandeiras', 18, 'CV'),
('De que país é esta bandeira?', '["Maurícia", "França", "Reunião", "Madagáscar"]', 2, '/flags/re.svg', 'Bandeiras', 18, 'RE'),
('De que país é esta bandeira?', '["Bermudas", "Canadá", "Estados Unidos", "Reino Unido"]', 0, '/flags/bm.svg', 'Bandeiras', 18, 'BM'),
('De que país é esta bandeira?', '["Estados Unidos", "Canadá", "França", "Reino Unido"]', 1, '/flags/ca.svg', 'Bandeiras', 18, 'CA'),
('De que país é esta bandeira?', '["Barbados", "Bahamas", "Jamaica", "Trinidad e Tobago"]', 3, '/flags/tt.svg', 'Bandeiras', 18, 'TT'),
('De que país é esta bandeira?', '["República Democrática do Congo", "Gabão", "Angola", "República do Congo"]', 3, '/flags/cg.svg', 'Bandeiras', 18, 'CG'),
('De que país é esta bandeira?', '["Singapura", "Brunei", "Indonésia", "Malásia"]', 1, '/flags/bn.svg', 'Bandeiras', 18, 'BN'),
('De que país é esta bandeira?', '["Nova Zelândia", "Quiribati", "Fiji", "Tuvalu"]', 3, '/flags/tv.svg', 'Bandeiras', 18, 'TV'),
('De que país é esta bandeira?', '["Jamaica", "Barbados", "Bahamas", "Trinidad e Tobago"]', 1, '/flags/bb.svg', 'Bandeiras', 18, 'BB'),
('De que país é esta bandeira?', '["Laos", "Vietname", "Camboja", "Tailândia"]', 1, '/flags/vn.svg', 'Bandeiras', 18, 'VN'),
('De que país é esta bandeira?', '["Panamá", "Nicarágua", "Colômbia", "Costa Rica"]', 0, '/flags/pa.svg', 'Bandeiras', 18, 'PA'),
('De que país é esta bandeira?', '["Nepal", "Índia", "Butão", "China"]', 2, '/flags/bt.svg', 'Bandeiras', 18, 'BT'),
('De que país é esta bandeira?', '["Eslováquia", "Ucrânia", "Polónia", "República Checa"]', 2, '/flags/pl.svg', 'Bandeiras', 18, 'PL'),
('De que país é esta bandeira?', '["Turquia", "Síria", "Grécia", "Chipre"]', 0, '/flags/tr.svg', 'Bandeiras', 18, 'TR'),
('De que país é esta bandeira?', '["Estónia", "Letónia", "Polónia", "Lituânia"]', 1, '/flags/lv.svg', 'Bandeiras', 18, 'LV'),
('De que país é esta bandeira?', '["Colômbia", "Venezuela", "Peru", "Equador"]', 0, '/flags/co.svg', 'Bandeiras', 18, 'CO'),
('De que país é esta bandeira?', '["França", "Vaticano", "San Marino", "Itália"]', 2, '/flags/sm.svg', 'Bandeiras', 18, 'SM'),
('De que país é esta bandeira?', '["Senegal", "Mali", "Níger", "Burkina Faso"]', 1, '/flags/ml.svg', 'Bandeiras', 18, 'ML'),
('De que país é esta bandeira?', '["República do Congo", "Camarões", "Guiné Equatorial", "Gabão"]', 3, '/flags/ga.svg', 'Bandeiras', 18, 'GA'),
('De que país é esta bandeira?', '["Ruanda", "Uganda", "República Democrática do Congo", "República do Congo"]', 2, '/flags/cd.svg', 'Bandeiras', 18, 'CD'),
('De que país é esta bandeira?', '["Tailândia", "Laos", "Camboja", "Vietname"]', 2, '/flags/kh.svg', 'Bandeiras', 18, 'KH'),
('De que país é esta bandeira?', '["Singapura", "Japão", "China", "Hong Kong"]', 3, '/flags/hk.svg', 'Bandeiras', 18, 'HK'),
('De que país é esta bandeira?', '["Guiné", "Senegal", "Mauritânia", "Gâmbia"]', 3, '/flags/gm.svg', 'Bandeiras', 18, 'GM'),
('De que país é esta bandeira?', '["Croácia", "Bósnia-Herzegovina", "Sérvia", "Montenegro"]', 1, '/flags/ba.svg', 'Bandeiras', 18, 'BA'),
('De que país é esta bandeira?', '["Libéria", "Serra Leoa", "Guiné", "Costa do Marfim"]', 0, '/flags/lr.svg', 'Bandeiras', 18, 'LR'),
('De que país é esta bandeira?', '["Fiji", "Nova Caledónia", "Vanuatu", "Austrália"]', 1, '/flags/nc.svg', 'Bandeiras', 18, 'NC'),
('De que país é esta bandeira?', '["Anguilla", "Ilhas Virgens Britânicas", "São Cristóvão e Nevis", "Reino Unido"]', 0, '/flags/ai.svg', 'Bandeiras', 18, 'AI'),
('De que país é esta bandeira?', '["Paquistão", "Iraque", "Afeganistão", "Irão"]', 3, '/flags/ir.svg', 'Bandeiras', 18, 'IR'),
('De que país é esta bandeira?', '["Moldávia", "Ucrânia", "Rússia", "Bielorrússia"]', 1, '/flags/ua.svg', 'Bandeiras', 18, 'UA'),
('De que país é esta bandeira?', '["Albânia", "Bulgária", "Macedónia do Norte", "Grécia"]', 2, '/flags/mk.svg', 'Bandeiras', 18, 'MK'),
('De que país é esta bandeira?', '["Nova Zelândia", "Reino Unido", "Irlanda", "Austrália"]', 1, '/flags/gb.svg', 'Bandeiras', 18, 'GB'),
('De que país é esta bandeira?', '["Senegal", "Guiné", "Mali", "Mauritânia"]', 0, '/flags/sn.svg', 'Bandeiras', 18, 'SN'),
('De que país é esta bandeira?', '["Palestina", "Jordânia", "Líciano", "Israel"]', 3, '/flags/il.svg', 'Bandeiras', 18, 'IL'),
('De que país é esta bandeira?', '["Santa Helena", "Reino Unido", "Brasil", "África do Sul"]', 0, '/flags/sh.svg', 'Bandeiras', 18, 'SH'),
('De que país é esta bandeira?', '["Togo", "Gana", "Burkina Faso", "Benin"]', 0, '/flags/tg.svg', 'Bandeiras', 18, 'TG'),
('De que país é esta bandeira?', '["Samoa", "Fiji", "Nova Zelândia", "Tonga"]', 3, '/flags/to.svg', 'Bandeiras', 18, 'TO'),
('De que país é esta bandeira?', '["Coreia do Sul", "Japão", "Vietname", "China"]', 1, '/flags/jp.svg', 'Bandeiras', 18, 'JP'),
('De que país é esta bandeira?', '["Laos", "Tailândia", "Vietname", "Camboja"]', 0, '/flags/la.svg', 'Bandeiras', 18, 'LA'),
('De que país é esta bandeira?', '["Chipre", "Malta", "Itália", "Grécia"]', 1, '/flags/mt.svg', 'Bandeiras', 18, 'MT'),
('De que país é esta bandeira?', '["Guatemala", "El Salvador", "Nicarágua", "Honduras"]', 0, '/flags/gt.svg', 'Bandeiras', 18, 'GT'),
('De que país é esta bandeira?', '["Suíça", "Alemanha", "Áustria", "Hungria"]', 2, '/flags/at.svg', 'Bandeiras', 18, 'AT'),
('De que país é esta bandeira?', '["Itália", "Espanha", "Grécia", "França"]', 0, '/flags/it.svg', 'Bandeiras', 18, 'IT'),
('De que país é esta bandeira?', '["Arábia Saudita", "Koweit", "Qatar", "Emirados Árabes Unidos"]', 2, '/flags/qa.svg', 'Bandeiras', 18, 'QA'),
('De que país é esta bandeira?', '["Omã", "Arábia Saudita", "Qatar", "Emirados Árabes Unidos"]', 1, '/flags/sa.svg', 'Bandeiras', 18, 'SA'),
('De que país é esta bandeira?', '["Malawi", "Zâmbia", "Moçambique", "Zimbabwe"]', 1, '/flags/zm.svg', 'Bandeiras', 18, 'ZM'),
('De que país é esta bandeira?', '["Moçambique", "Botswana", "Zâmbia", "Zimbabwe"]', 3, '/flags/zw.svg', 'Bandeiras', 18, 'ZW'),
('De que país é esta bandeira?', '["Malásia", "Indonésia", "Singapura", "Brunei"]', 1, '/flags/id.svg', 'Bandeiras', 18, 'ID'),
('De que país é esta bandeira?', '["Emirados Árabes Unidos", "Arábia Saudita", "Iraque", "Koweit"]', 3, '/flags/kw.svg', 'Bandeiras', 18, 'KW'),
('De que país é esta bandeira?', '["Eritreia", "Somália", "Etiópia", "Djibouti"]', 3, '/flags/dj.svg', 'Bandeiras', 18, 'DJ'),
('De que país é esta bandeira?', '["Porto Rico", "Cuba", "Haiti", "República Dominicana"]', 3, '/flags/do.svg', 'Bandeiras', 18, 'DO'),
('De que país é esta bandeira?', '["Eslováquia", "Hungria", "Polónia", "República Checa"]', 3, '/flags/cz.svg', 'Bandeiras', 18, 'CZ'),
('De que país é esta bandeira?', '["Nigéria", "Quénia", "África do Sul", "Gana"]', 2, '/flags/za.svg', 'Bandeiras', 18, 'ZA'),
('De que país é esta bandeira?', '["Sérvia", "Bósnia", "Croácia", "Eslovénia"]', 0, '/flags/rs.svg', 'Bandeiras', 18, 'RS'),
('De que país é esta bandeira?', '["Bangladesh", "Índia", "Mianmar", "Sri Lanka"]', 0, '/flags/bd.svg', 'Bandeiras', 18, 'BD'),
('De que país é esta bandeira?', '["Uganda", "Quénia", "Ruanda", "Tanzânia"]', 0, '/flags/ug.svg', 'Bandeiras', 18, 'UG'),
('De que país é esta bandeira?', '["Roménia", "Moldávia", "Ucrânia", "Rússia"]', 1, '/flags/md.svg', 'Bandeiras', 18, 'MD'),
('De que país é esta bandeira?', '["Ilhas Salomão", "Austrália", "Fiji", "Papua Nova Guiné"]', 0, '/flags/sb.svg', 'Bandeiras', 18, 'SB'),
('De que país é esta bandeira?', '["Indonésia", "Índia", "Sri Lanka", "Maldivas"]', 3, '/flags/mv.svg', 'Bandeiras', 18, 'MV'),
('De que país é esta bandeira?', '["França", "Jersey", "Guernsey", "Reino Unido"]', 1, '/flags/je.svg', 'Bandeiras', 18, 'JE'),
('De que país é esta bandeira?', '["Peru", "Colômbia", "Venezuela", "Brasil"]', 2, '/flags/ve.svg', 'Bandeiras', 18, 'VE'),
('De que país é esta bandeira?', '["Bielorrússia", "Rússia", "Ucrânia", "Cazaquistão"]', 1, '/flags/ru.svg', 'Bandeiras', 18, 'RU'),
('De que país é esta bandeira?', '["Irlanda", "Reino Unido", "Escócia", "País de Gales"]', 0, '/flags/ie.svg', 'Bandeiras', 18, 'IE'),
('De que país é esta bandeira?', '["Namíbia", "Zimbabwe", "Botswana", "África do Sul"]', 2, '/flags/bw.svg', 'Bandeiras', 18, 'BW'),
('De que país é esta bandeira?', '["Eslovénia", "Croácia", "Bósnia", "Sérvia"]', 1, '/flags/hr.svg', 'Bandeiras', 18, 'HR'),
('De que país é esta bandeira?', '["Coreia do Sul", "China", "Japão", "Singapura"]', 0, '/flags/kr.svg', 'Bandeiras', 18, 'KR'),
('De que país é esta bandeira?', '["Quirguistão", "Cazaquistão", "Turquemenistão", "Uzbequistão"]', 1, '/flags/kz.svg', 'Bandeiras', 18, 'KZ'),
('De que país é esta bandeira?', '["Fiji", "Nova Zelândia", "Quiribati", "Samoa"]', 2, '/flags/ki.svg', 'Bandeiras', 18, 'KI'),
('De que país é esta bandeira?', '["Timor-Leste", "Portugal", "Indonésia", "Austrália"]', 0, '/flags/tl.svg', 'Bandeiras', 18, 'TL'),
('De que país é esta bandeira?', '["Polónia", "República Checa", "Eslováquia", "Eslovénia"]', 2, '/flags/sk.svg', 'Bandeiras', 18, 'SK'),
('De que país é esta bandeira?', '["Itália", "Macedónia", "Albânia", "Grécia"]', 2, '/flags/al.svg', 'Bandeiras', 18, 'AL'),
('De que país é esta bandeira?', '["Martinica", "São Martinho", "Guadalupe", "França"]', 2, '/flags/gp.svg', 'Bandeiras', 18, 'GP'),
('De que país é esta bandeira?', '["Sudão", "Egipto", "Etiiópia", "Eritreia"]', 0, '/flags/sd.svg', 'Bandeiras', 18, 'SD'),
('De que país é esta bandeira?', '["Filipinas", "Austrália", "Estados Unidos", "Guam"]', 3, '/flags/gu.svg', 'Bandeiras', 18, 'GU'),
('De que país é esta bandeira?', '["Rússia", "Geórgia", "Turquia", "Azerbaijão"]', 1, '/flags/ge.svg', 'Bandeiras', 18, 'GE'),
('De que país é esta bandeira?', '["Chipre", "Itália", "Grécia", "Albânia"]', 2, '/flags/gr.svg', 'Bandeiras', 18, 'GR'),
('De que país é esta bandeira?', '["Marrocos", "Argélia", "Tunísia", "Egito"]', 0, '/flags/ma.svg', 'Bandeiras', 18, 'MA'),
('De que país é esta bandeira?', '["Albânia", "Sérvia", "Montenegro", "Kosovo"]', 3, '/flags/xk.svg', 'Bandeiras', 18, 'XK'),
('De que país é esta bandeira?', '["Nepal", "Índia", "China", "Butão"]', 0, '/flags/np.svg', 'Bandeiras', 18, 'NP'),
('De que país é esta bandeira?', '["Jordânia", "Síria", "Iraque", "Israel"]', 0, '/flags/jo.svg', 'Bandeiras', 18, 'JO'),
('De que país é esta bandeira?', '["Arménia", "Rússia", "Azerbaijão", "Irão"]', 2, '/flags/az.svg', 'Bandeiras', 18, 'AZ'),
('De que país é esta bandeira?', '["México", "Guatemala", "Honduras", "Belize"]', 3, '/flags/bz.svg', 'Bandeiras', 18, 'BZ'),
('De que país é esta bandeira?', '["Porto Rico", "Ilhas Caimão", "Anguilla", "Ilhas Virgens Britânicas"]', 3, '/flags/vg.svg', 'Bandeiras', 18, 'VG'),
('De que país é esta bandeira?', '["Antilhas Holandesas", "Venezuela", "Curaçao", "Aruba"]', 2, '/flags/cw.svg', 'Bandeiras', 18, 'CW'),
('De que país é esta bandeira?', '["Bolívia", "Peru", "Paraguai", "Chile"]', 0, '/flags/bo.svg', 'Bandeiras', 18, 'BO'),
('De que país é esta bandeira?', '["Nicarágua", "El Salvador", "Guatemala", "Honduras"]', 1, '/flags/sv.svg', 'Bandeiras', 18, 'SV'),
('De que país é esta bandeira?', '["Singapura", "Malásia", "Brunei", "Indonésia"]', 0, '/flags/sg.svg', 'Bandeiras', 18, 'SG'),
('De que país é esta bandeira?', '["Malásia", "Brunei", "Indonésia", "Singapura"]', 0, '/flags/my.svg', 'Bandeiras', 18, 'MY'),
('De que país é esta bandeira?', '["Holanda", "Bélgica", "Luxemburgo", "Dinamarca"]', 0, '/flags/nl.svg', 'Bandeiras', 18, 'NL'),
('De que país é esta bandeira?', '["Estónia", "Rússia", "Lituânia", "Letónia"]', 0, '/flags/ee.svg', 'Bandeiras', 18, 'EE'),
('De que país é esta bandeira?', '["Angola", "Moçambique", "Namíbia", "República do Congo"]', 0, '/flags/ao.svg', 'Bandeiras', 18, 'AO'),
('De que país é esta bandeira?', '["Holanda", "França", "São Martinho", "Antilhas Holandesas"]', 2, '/flags/mf.svg', 'Bandeiras', 18, 'MF'),
('De que país é esta bandeira?', '["Bélgica", "Reino Unido", "Alemanha", "França"]', 3, '/flags/fr.svg', 'Bandeiras', 18, 'FR'),
('De que país é esta bandeira?', '["Itália", "França", "Portugal", "Espanha"]', 2, '/flags/pt.svg', 'Bandeiras', 18, 'PT'),
('De que país é esta bandeira?', '["Peru", "Equador", "Chile", "Bolívia"]', 0, '/flags/pe.svg', 'Bandeiras', 18, 'PE'),
('De que país é esta bandeira?', '["Tanzânia", "Uganda", "Quénia", "Ruanda"]', 0, '/flags/tz.svg', 'Bandeiras', 18, 'TZ'),
('De que país é esta bandeira?', '["Austrália", "Nova Zelândia", "Polinésia Francesa", "Hawai"]', 2, '/flags/pf.svg', 'Bandeiras', 18, 'PF'),
('De que país é esta bandeira?', '["Omã", "Arábia Saudita", "Djibouti", "Iémen"]', 3, '/flags/ye.svg', 'Bandeiras', 18, 'YE'),
('De que país é esta bandeira?', '["Irlanda", "Reino Unido", "Ilha de Man", "Escócia"]', 2, '/flags/im.svg', 'Bandeiras', 18, 'IM'),
('De que país é esta bandeira?', '["Holanda", "Bélgica", "França", "Luxemburgo"]', 3, '/flags/lu.svg', 'Bandeiras', 18, 'LU'),
('De que país é esta bandeira?', '["Nicarágua", "Honduras", "El Salvador", "Guatemala"]', 1, '/flags/hn.svg', 'Bandeiras', 18, 'HN'),
('De que país é esta bandeira?', '["Marrocos", "Senegal", "Mauritânia", "Mali"]', 2, '/flags/mr.svg', 'Bandeiras', 18, 'MR'),
('De que país é esta bandeira?', '["Papua Nova Guiné", "Tonga", "Samoa", "Fiji"]', 3, '/flags/fj.svg', 'Bandeiras', 18, 'FJ'),
('De que país é esta bandeira?', '["Roménia", "Bulgária", "Moldávia", "Hungria"]', 0, '/flags/ro.svg', 'Bandeiras', 18, 'RO'),
('De que país é esta bandeira?', '["Samoa", "Nova Zelândia", "Fiji", "Tonga"]', 0, '/flags/ws.svg', 'Bandeiras', 18, 'WS'),
('De que país é esta bandeira?', '["Níger", "Mali", "Burkina Faso", "Benin"]', 2, '/flags/bf.svg', 'Bandeiras', 18, 'BF'),
('De que país é esta bandeira?', '["Botswana", "África do Sul", "Suazilândia", "Lesoto"]', 3, '/flags/ls.svg', 'Bandeiras', 18, 'LS'),
('De que país é esta bandeira?', '["Rússia", "Mongólia", "Cazaquistão", "China"]', 1, '/flags/mn.svg', 'Bandeiras', 18, 'MN'),
('De que país é esta bandeira?', '["Jamaica", "República Dominicana", "Haiti", "Cuba"]', 3, '/flags/cu.svg', 'Bandeiras', 18, 'CU'),
('De que país é esta bandeira?', '["Reino Unido", "Portugal", "Gibraltar", "Espanha"]', 2, '/flags/gi.svg', 'Bandeiras', 18, 'GI'),
('De que país é esta bandeira?', '["Argentina", "Paraguai", "Uruguai", "Bolívia"]', 1, '/flags/py.svg', 'Bandeiras', 18, 'PY'),
('De que país é esta bandeira?', '["Guiné Equatorial", "São Tomé e Príncipe", "Nigéria", "Gabão"]', 1, '/flags/st.svg', 'Bandeiras', 18, 'ST'),
('De que país é esta bandeira?', '["Tunísia", "Argélia", "Egito", "Marrocos"]', 2, '/flags/eg.svg', 'Bandeiras', 18, 'EG'),
('De que país é esta bandeira?', '["Noruega", "Suécia", "Dinamarca", "Finlândia"]', 2, '/flags/dk.svg', 'Bandeiras', 18, 'DK'),
('De que país é esta bandeira?', '["Qatar", "Arábia Saudita", "Koweit", "Emirados Árabes Unidos"]', 3, '/flags/ae.svg', 'Bandeiras', 18, 'AE'),
('De que país é esta bandeira?', '["Groenlândia", "Islândia", "Finlândia", "Noruega"]', 1, '/flags/is.svg', 'Bandeiras', 18, 'IS'),
('De que país é esta bandeira?', '["Dinamarca", "Suécia", "Islândia", "Noruega"]', 3, '/flags/no.svg', 'Bandeiras', 18, 'NO'),
('De que país é esta bandeira?', '["Comores", "Maurícia", "Seicheles", "Madagáscar"]', 1, '/flags/mu.svg', 'Bandeiras', 18, 'MU'),
('De que país é esta bandeira?', '["Malásia", "Singapura", "Indonésia", "Filipinas"]', 3, '/flags/ph.svg', 'Bandeiras', 18, 'PH'),
('De que país é esta bandeira?', '["Bahamas", "Cuba", "Jamaica", "Porto Rico"]', 0, '/flags/bs.svg', 'Bandeiras', 18, 'BS'),
('De que país é esta bandeira?', '["Antilhas Holandesas", "Holanda", "Colômbia", "Aruba"]', 3, '/flags/aw.svg', 'Bandeiras', 18, 'AW')

ON CONFLICT DO NOTHING;
