-- ATUALIZAR TODAS AS BANDEIRAS PARA USAR CAMINHOS LOCAIS
-- Executar no SQL Editor do Supabase Dashboard
-- Este script atualiza as URLs das bandeiras para usar /flags/xx.svg (caminho local)

-- Primeiro, vamos ver quantas perguntas de bandeiras existem
-- SELECT COUNT(*) FROM questions WHERE category = 'Bandeiras';

-- Atualizar perguntas existentes de bandeiras que têm URLs do flagcdn.com
-- Extrair o código do país da URL e criar caminho local

UPDATE questions 
SET image_url = '/flags/' || 
    CASE 
        WHEN image_url LIKE '%/pt.svg' THEN 'pt'
        WHEN image_url LIKE '%/br.svg' THEN 'br'
        WHEN image_url LIKE '%/es.svg' THEN 'es'
        WHEN image_url LIKE '%/fr.svg' THEN 'fr'
        WHEN image_url LIKE '%/de.svg' THEN 'de'
        WHEN image_url LIKE '%/it.svg' THEN 'it'
        WHEN image_url LIKE '%/gb.svg' THEN 'gb'
        WHEN image_url LIKE '%/us.svg' THEN 'us'
        WHEN image_url LIKE '%/jp.svg' THEN 'jp'
        WHEN image_url LIKE '%/cn.svg' THEN 'cn'
        WHEN image_url LIKE '%/kr.svg' THEN 'kr'
        WHEN image_url LIKE '%/in.svg' THEN 'in'
        WHEN image_url LIKE '%/ru.svg' THEN 'ru'
        WHEN image_url LIKE '%/au.svg' THEN 'au'
        WHEN image_url LIKE '%/ca.svg' THEN 'ca'
        WHEN image_url LIKE '%/mx.svg' THEN 'mx'
        WHEN image_url LIKE '%/ar.svg' THEN 'ar'
        WHEN image_url LIKE '%/nl.svg' THEN 'nl'
        WHEN image_url LIKE '%/be.svg' THEN 'be'
        WHEN image_url LIKE '%/ch.svg' THEN 'ch'
        WHEN image_url LIKE '%/at.svg' THEN 'at'
        WHEN image_url LIKE '%/gr.svg' THEN 'gr'
        WHEN image_url LIKE '%/se.svg' THEN 'se'
        WHEN image_url LIKE '%/no.svg' THEN 'no'
        WHEN image_url LIKE '%/dk.svg' THEN 'dk'
        WHEN image_url LIKE '%/fi.svg' THEN 'fi'
        WHEN image_url LIKE '%/ie.svg' THEN 'ie'
        WHEN image_url LIKE '%/pl.svg' THEN 'pl'
        WHEN image_url LIKE '%/ua.svg' THEN 'ua'
        WHEN image_url LIKE '%/cz.svg' THEN 'cz'
        WHEN image_url LIKE '%/hu.svg' THEN 'hu'
        WHEN image_url LIKE '%/ro.svg' THEN 'ro'
        WHEN image_url LIKE '%/bg.svg' THEN 'bg'
        WHEN image_url LIKE '%/rs.svg' THEN 'rs'
        WHEN image_url LIKE '%/hr.svg' THEN 'hr'
        WHEN image_url LIKE '%/si.svg' THEN 'si'
        WHEN image_url LIKE '%/sk.svg' THEN 'sk'
        WHEN image_url LIKE '%/cl.svg' THEN 'cl'
        WHEN image_url LIKE '%/co.svg' THEN 'co'
        WHEN image_url LIKE '%/pe.svg' THEN 'pe'
        WHEN image_url LIKE '%/ve.svg' THEN 've'
        WHEN image_url LIKE '%/ec.svg' THEN 'ec'
        WHEN image_url LIKE '%/bo.svg' THEN 'bo'
        WHEN image_url LIKE '%/uy.svg' THEN 'uy'
        WHEN image_url LIKE '%/py.svg' THEN 'py'
        WHEN image_url LIKE '%/cu.svg' THEN 'cu'
        WHEN image_url LIKE '%/jm.svg' THEN 'jm'
        WHEN image_url LIKE '%/cr.svg' THEN 'cr'
        WHEN image_url LIKE '%/pa.svg' THEN 'pa'
        WHEN image_url LIKE '%/gt.svg' THEN 'gt'
        WHEN image_url LIKE '%/th.svg' THEN 'th'
        WHEN image_url LIKE '%/vn.svg' THEN 'vn'
        WHEN image_url LIKE '%/id.svg' THEN 'id'
        WHEN image_url LIKE '%/ph.svg' THEN 'ph'
        WHEN image_url LIKE '%/sg.svg' THEN 'sg'
        WHEN image_url LIKE '%/my.svg' THEN 'my'
        WHEN image_url LIKE '%/mm.svg' THEN 'mm'
        WHEN image_url LIKE '%/bd.svg' THEN 'bd'
        WHEN image_url LIKE '%/pk.svg' THEN 'pk'
        WHEN image_url LIKE '%/af.svg' THEN 'af'
        WHEN image_url LIKE '%/ae.svg' THEN 'ae'
        WHEN image_url LIKE '%/sa.svg' THEN 'sa'
        WHEN image_url LIKE '%/il.svg' THEN 'il'
        WHEN image_url LIKE '%/ir.svg' THEN 'ir'
        WHEN image_url LIKE '%/iq.svg' THEN 'iq'
        WHEN image_url LIKE '%/eg.svg' THEN 'eg'
        WHEN image_url LIKE '%/za.svg' THEN 'za'
        WHEN image_url LIKE '%/ma.svg' THEN 'ma'
        WHEN image_url LIKE '%/ng.svg' THEN 'ng'
        WHEN image_url LIKE '%/ke.svg' THEN 'ke'
        WHEN image_url LIKE '%/gh.svg' THEN 'gh'
        WHEN image_url LIKE '%/tz.svg' THEN 'tz'
        WHEN image_url LIKE '%/tn.svg' THEN 'tn'
        WHEN image_url LIKE '%/dz.svg' THEN 'dz'
        WHEN image_url LIKE '%/et.svg' THEN 'et'
        WHEN image_url LIKE '%/nz.svg' THEN 'nz'
        WHEN image_url LIKE '%/fj.svg' THEN 'fj'
        WHEN image_url LIKE '%/pg.svg' THEN 'pg'
        WHEN image_url LIKE '%/tw.svg' THEN 'tw'
        WHEN image_url LIKE '%/kz.svg' THEN 'kz'
        WHEN image_url LIKE '%/by.svg' THEN 'by'
        ELSE NULL
    END || '.svg'
WHERE category = 'Bandeiras' 
AND image_url LIKE '%flagcdn.com%';
